import type { WordPack } from '../types'
import { buildPairs, type PairSeed } from './build'

/**
 * Asian American: diaspora-fluent, affectionate pairs. Never othering.
 *
 * Every matchup is explicit so pair quality never depends on category ordering.
 */
const seeds = [
  // Dining out
  ['boba shop', 'dessert cafe', ['dining-out']],
  ['H Mart', "Trader Joe's", ['grocery']],
  ['Korean BBQ', 'hot pot', ['dining-out']],
  ['dim sum', 'brunch', ['dining-out']],
  ['ramen shop', 'pho shop', ['dining-out']],
  ['sushi bar', 'sake bar', ['dining-out']],
  ['night market', 'food hall', ['dining-out']],
  ['Daiso', 'Muji', ['shopping']],
  ['Japanese market', 'Korean market', ['grocery']],
  ['Panda Express', 'Chinese takeout', ['restaurants']],
  ['dumpling restaurant', 'hot pot restaurant', ['restaurants']],
  ['Chinese bakery', 'French bakery', ['restaurants']],
  ['food court', 'night market', ['dining-out']],
  ['buffet', 'family style', ['dining-out']],
  ['takeout', 'delivery', ['dining-out']],
  ['tea house', 'coffee shop', ['dining-out']],
  ['bakery', 'dessert cafe', ['dining-out']],
  ['ramen shop', 'sushi bar', ['dining-out']],
  ['karaoke bar', 'soju bar', ['nightlife']],
  ['karaoke', 'open mic', ['nightlife']],

  // Rice, noodles, and dumplings
  ['rice', 'noodles', ['staples']],
  ['fried rice', 'chow mein', ['food']],
  ['jasmine rice', 'sticky rice', ['staples']],
  ['jasmine rice', 'basmati rice', ['staples']],
  ['white rice', 'brown rice', ['staples']],
  ['rice noodles', 'egg noodles', ['staples']],
  ['glass noodles', 'rice noodles', ['staples']],
  ['ramen', 'udon', ['noodles']],
  ['udon', 'soba', ['noodles']],
  ['pho', 'ramen', ['noodle-soup']],
  ['wonton soup', 'miso soup', ['soup']],
  ['wonton soup', 'pho', ['noodle-soup']],
  ['pad thai', 'chow mein', ['noodles']],
  ['glass noodles', 'lo mein', ['noodles']],
  ['lo mein', 'chow mein', ['noodles']],
  ['rice porridge', 'oatmeal', ['porridge']],
  ['rice porridge', 'grits', ['porridge']],
  ['potsticker', 'wonton', ['dumplings']],
  ['steamed dumpling', 'fried dumpling', ['dumplings']],
  ['soup dumpling', 'pork dumpling', ['dim-sum']],
  ['shrimp dumpling', 'pork dumpling', ['dim-sum']],
  ['egg roll', 'spring roll', ['food']],
  ['fried spring roll', 'fresh spring roll', ['food']],

  // Mains, sides, and breads
  ['kimbap', 'sushi', ['food']],
  ['rice ball', 'sushi roll', ['food']],
  ['banh mi', 'sub sandwich', ['food']],
  ['Korean BBQ', 'Japanese BBQ', ['food']],
  ['BBQ pork', 'roast duck', ['roast-meat']],
  ['Peking duck', 'roast pork', ['roast-meat']],
  ['chicken cutlet', 'tempura', ['fried-food']],
  ['pork cutlet', 'chicken cutlet', ['fried-food']],
  ['bibimbap', 'fried rice', ['rice-dishes']],
  ['curry rice', 'curry noodles', ['curry']],
  ['Japanese curry', 'Thai curry', ['curry']],
  ['green curry', 'red curry', ['curry']],
  ['butter chicken', 'tikka masala', ['curry']],
  ['mapo tofu', 'soondubu', ['tofu']],
  ['miso soup', 'seaweed soup', ['soup']],
  ['hot pot', 'fondue', ['food']],
  ['scallion pancake', 'naan', ['flatbread']],
  ['naan', 'pita', ['flatbread']],
  ['milk bread', 'Hawaiian roll', ['bread']],
  ['kimchi', 'pickled radish', ['side-dishes']],
  ['banchan', 'tapas', ['small-plates']],
  ['seaweed salad', 'cucumber salad', ['side-dishes']],

  // Desserts, fruit, and snacks
  ['mochi', 'egg tart', ['dessert']],
  ['egg tart', 'pineapple bun', ['bakery']],
  ['mooncake', 'pineapple cake', ['bakery']],
  ['coconut', 'matcha', ['flavors']],
  ['black sesame', 'red bean', ['flavors']],
  ['mango pudding', 'rice pudding', ['dessert']],
  ['shaved ice', 'ice cream', ['dessert']],
  ['snow cone', 'shaved ice', ['dessert']],
  ['mochi donut', 'egg waffle', ['dessert']],
  ['custard bun', 'sesame ball', ['dim-sum']],
  ['red bean soup', 'black sesame soup', ['dessert']],
  ['Pocky', 'Hello Panda', ['snacks']],
  ['Pocky', 'shrimp chips', ['snacks']],
  ['Hi-Chew', 'White Rabbit', ['candy']],
  ['shrimp chips', 'seaweed snacks', ['snacks']],
  ['rice crackers', 'shrimp chips', ['snacks']],
  ['lychee jelly', 'grass jelly', ['dessert']],
  ['fortune cookie', 'almond cookie', ['cookies']],
  ['lychee', 'mango', ['fruit']],
  ['durian', 'jackfruit', ['fruit']],
  ['Asian pear', 'apple', ['fruit']],
  ['coconut', 'red bean', ['flavors']],
  ['yuzu', 'lime', ['citrus']],

  // Drinks, sauces, and groceries
  ['bubble tea', 'Thai tea', ['drinks']],
  ['milk tea', 'matcha latte', ['drinks']],
  ['Vietnamese coffee', 'Thai tea', ['drinks']],
  ['Hong Kong milk tea', 'Thai tea', ['drinks']],
  ['oolong tea', 'jasmine tea', ['tea']],
  ['green tea', 'milk tea', ['tea']],
  ['yogurt drink', 'milk tea', ['drinks']],
  ['soda', 'yogurt drink', ['drinks']],
  ['sugarcane juice', 'coconut water', ['drinks']],
  ['mango lassi', 'mango smoothie', ['drinks']],
  ['soju', 'sake', ['alcohol']],
  ['sake', 'beer', ['alcohol']],
  ['soju', 'vodka', ['alcohol']],
  ['sriracha', 'chili crisp', ['condiments']],
  ['soy sauce', 'fish sauce', ['condiments']],
  ['hoisin sauce', 'oyster sauce', ['condiments']],
  ['miso', 'gochujang', ['condiments']],
  ['chili paste', 'curry paste', ['condiments']],
  ['wasabi', 'hot mustard', ['condiments']],
  ['chili oil', 'sesame oil', ['condiments']],
  ['rice vinegar', 'black vinegar', ['condiments']],
  ['sesame seeds', 'everything seasoning', ['toppings']],
  ['tofu', 'tempeh', ['ingredients']],
  ['cabbage', 'bok choy', ['vegetables']],

  // Home and kitchen
  ['rice cooker', 'Instant Pot', ['kitchen']],
  ['wok', 'frying pan', ['kitchen']],
  ['cleaver', "chef's knife", ['kitchen']],
  ['bamboo steamer', 'steamer basket', ['kitchen']],
  ['clay pot', 'Dutch oven', ['kitchen']],
  ['electric kettle', 'stovetop kettle', ['kitchen']],
  ['chopsticks', 'fork', ['tableware']],
  ['soup spoon', 'teaspoon', ['tableware']],
  ['rice paddle', 'spatula', ['kitchen']],
  ['tea thermos', 'water bottle', ['home']],
  ['lunch box', 'picnic basket', ['home']],
  ['shoe rack', 'coat rack', ['home']],
  ['house slippers', 'socks', ['home']],
  ['plastic stool', 'folding chair', ['home']],
  ['card table', 'dining table', ['home']],
  ['lazy Susan', 'serving tray', ['dining']],
  ['teapot', 'coffee pot', ['home']],
  ['incense', 'scented candle', ['home']],
  ['orchid', 'lucky bamboo', ['plants']],
  ['jade bracelet', 'gold necklace', ['jewelry']],
  ['red envelope', 'gift card', ['gifts']],
  ['air fryer', 'toaster oven', ['kitchen']],
  ['portable grill', 'hot plate', ['kitchen']],

  // Family and childhood
  ['auntie', 'uncle', ['family']],
  ['grandma', 'grandpa', ['family']],
  ['older sibling', 'younger sibling', ['family']],
  ['tiger parent', 'helicopter parent', ['family']],
  ['family group chat', 'friend group chat', ['messaging']],
  ['WeChat', 'WhatsApp', ['messaging']],
  ['WeChat', 'FaceTime', ['messaging']],
  ['voice message', 'phone call', ['messaging']],
  ['calling home', 'visiting home', ['family']],
  ['family dinner', 'family reunion', ['family']],
  ['potluck', 'banquet', ['gatherings']],
  ['Chinese school', 'Sunday school', ['childhood']],
  ['Chinese school', 'Korean school', ['childhood']],
  ['piano lesson', 'violin lesson', ['childhood']],
  ['Kumon', 'SAT prep', ['school']],
  ['math team', 'debate team', ['school']],
  ['spelling bee', 'math competition', ['school']],
  ['packed lunch', 'school lunch', ['school']],
  ['thermos', 'travel mug', ['school']],
  ['doctor', 'lawyer', ['careers']],
  ['engineer', 'accountant', ['careers']],
  ['med school', 'law school', ['school']],
  ['indoor slippers', 'socks', ['house-rules']],

  // Holidays, traditions, and games
  ['Lunar New Year', 'Thanksgiving', ['holidays']],
  ['Lunar New Year', 'Christmas', ['holidays']],
  ['Diwali', 'Thanksgiving', ['holidays']],
  ['Diwali', 'Lunar New Year', ['holidays']],
  ['Diwali', 'Christmas', ['holidays']],
  ['Christmas potluck', 'New Year banquet', ['holidays']],
  ['red envelope', 'Christmas stocking', ['holidays']],
  ['mooncake', 'rice dumpling', ['holiday-food']],
  ['birthday noodles', 'birthday cake', ['birthday']],
  ['lion dance', 'dragon dance', ['traditions']],
  ['firecrackers', 'sparklers', ['celebrations']],
  ['temple', 'church', ['community']],
  ['incense', 'prayer candle', ['traditions']],
  ['mahjong', 'poker', ['games']],
  ['mahjong', 'Uno', ['games']],
  ['Uno', 'poker', ['games']],
  ['mahjong', 'chess', ['games']],
  ['badminton', 'pickleball', ['sports']],
  ['table tennis', 'badminton', ['sports']],
  ['mahjong', 'rummy', ['gatherings']],
  ['red lantern', 'string lights', ['decorations']],
  ['lucky money', 'cash gift', ['gifts']],
  ['family banquet', 'wedding banquet', ['gatherings']],

  // Media and nightlife
  ['K-drama', 'C-drama', ['tv']],
  ['K-drama', 'J-drama', ['tv']],
  ['manga', 'webtoon', ['comics']],
  ['anime', 'manga', ['media']],
  ['subtitles', 'dubbing', ['media']],
  ['K-pop', 'J-pop', ['music']],
  ['boy band', 'girl group', ['music']],
  ['BTS', 'BLACKPINK', ['music']],
  ['Bollywood movie', 'Hollywood movie', ['movies']],
  ['variety show', 'reality show', ['tv']],
  ['cooking vlog', 'travel vlog', ['video']],
  ['rom-com', 'family drama', ['movies']],
  ['Studio Ghibli', 'Disney', ['movies']],
  ['karaoke room', 'private dining room', ['nightlife']],
  ['karaoke room', 'karaoke bar', ['karaoke']],
  ['soju bar', 'sake bar', ['nightlife']],
  ['arcade bar', 'board game cafe', ['nightlife']],
  ['karaoke booth', 'arcade', ['nightlife']],
  ['photo booth', 'karaoke booth', ['nightlife']],
  ['light stick', 'glow stick', ['music']],
  ['fan chant', 'singalong', ['music']],
  ['dance cover', 'music video', ['video']],
  ['streaming show', 'network show', ['tv']],

  // Beauty, style, and wellness
  ['sheet mask', 'eye patches', ['skincare']],
  ['sunscreen', 'tinted moisturizer', ['skincare']],
  ['makeup compact', 'foundation', ['makeup']],
  ['lip tint', 'lip gloss', ['makeup']],
  ['brow pencil', 'eyeliner', ['makeup']],
  ['oil cleanser', 'face wash', ['skincare']],
  ['face wash', 'moisturizer', ['skincare']],
  ['gua sha', 'jade roller', ['skincare']],
  ['hair oil', 'hair serum', ['haircare']],
  ['claw clip', 'scrunchie', ['hair']],
  ['perm', 'highlights', ['hair']],
  ['bangs', 'layers', ['hair']],
  ['nail salon', 'hair salon', ['beauty']],
  ['false lashes', 'lash extensions', ['beauty']],
  ['sheet mask', 'clay mask', ['skincare']],
  ['face serum', 'moisturizer', ['skincare']],
  ['rice water', 'rose water', ['skincare']],
  ['acupuncture', 'herbal medicine', ['wellness']],
  ['acupuncture', 'massage', ['wellness']],
  ['Tiger Balm', 'Vicks VapoRub', ['wellness']],
  ['qipao', 'hanbok', ['clothing']],
  ['sari', 'kimono', ['clothing']],
  ['jade pendant', 'gold chain', ['jewelry']],

  // Diaspora, travel, and community
  ['Chinatown', 'Koreatown', ['neighborhoods']],
  ['Chinatown', 'Little Tokyo', ['neighborhoods']],
  ['Japantown', 'Koreatown', ['neighborhoods']],
  ['passport', 'green card', ['documents']],
  ['Global Entry', 'TSA PreCheck', ['travel']],
  ['carry-on', 'checked bag', ['travel']],
  ['direct flight', 'layover', ['travel']],
  ['arrivals', 'departures', ['travel']],
  ['road trip', 'long-haul flight', ['travel']],
  ['family trip', 'friends trip', ['travel']],
  ['window seat', 'aisle seat', ['travel']],
  ['language school', 'music school', ['community']],
  ['nickname', 'middle name', ['identity']],
  ['last name', 'given name', ['identity']],
  ['bilingual', 'multilingual', ['language']],
  ['translator', 'interpreter', ['language']],
  ['subtitles', 'captions', ['language']],
  ['hometown', 'home country', ['identity']],
  ['family friend', 'distant cousin', ['family']],
  ['community center', 'public library', ['community']],
  ['street festival', 'night market', ['community']],
  ['Asian market', 'supermarket', ['shopping']],
  ['family photo', 'wedding photo', ['family']],
] as const satisfies readonly PairSeed[]

export const asianAmerican: WordPack = {
  id: "asian-american",
  name: "Asian American",
  description: "Diaspora-fluent picks for Asian American friend groups, affectionate and replayable.",
  builtIn: true,
  pairs: buildPairs("asian-american", seeds, [], 250),
}
