import type { WordPack } from '../types'

/**
 * Asian American: diaspora-fluent, affectionate pairs. Never othering.
 */
export const asianAmerican: WordPack = {
  id: 'asian-american',
  name: 'Asian American',
  description: 'Diaspora-fluent picks for AA friend groups — affectionate, never othering.',
  builtIn: true,
  pairs: [
    { id: 'asian-american-001', a: 'boba shop', b: 'dessert cafe', tags: ['food'] },
    { id: 'asian-american-002', a: 'h mart', b: '99 ranch', tags: ['grocery'] },
    { id: 'asian-american-003', a: 'kbbq', b: 'hot pot', tags: ['food'] },
    { id: 'asian-american-004', a: 'red envelope', b: 'gift card', tags: ['gifts'] },
    { id: 'asian-american-005', a: 'tiger parent', b: 'helicopter parent', tags: ['family'] },
    { id: 'asian-american-006', a: 'dim sum', b: 'brunch', tags: ['food'] },
    { id: 'asian-american-007', a: 'rice cooker', b: 'instant pot', tags: ['kitchen'] },
    { id: 'asian-american-008', a: 'lunar new year', b: 'thanksgiving', tags: ['holidays'] },
    { id: 'asian-american-009', a: 'mahjong', b: 'poker night', tags: ['games'] },
    { id: 'asian-american-010', a: 'ube', b: 'matcha', tags: ['flavors'] },
    { id: 'asian-american-011', a: 'ramen', b: 'pho', tags: ['food'] },
    { id: 'asian-american-012', a: 'sriracha', b: 'chili crisp', tags: ['condiments'] },
    { id: 'asian-american-013', a: 'karaoke room', b: 'noraebang', tags: ['nightlife'] },
    { id: 'asian-american-014', a: 'daiso', b: 'muji', tags: ['stores'] },
    { id: 'asian-american-015', a: 'sunday school', b: 'chinese school', tags: ['childhood'] },
    { id: 'asian-american-016', a: 'auntie', b: 'uncle', tags: ['family'] },
    { id: 'asian-american-017', a: 'take your shoes off', b: 'wash your hands', tags: ['house-rules'] },
    { id: 'asian-american-018', a: 'boba', b: 'thai tea', tags: ['drinks'] },
    { id: 'asian-american-019', a: 'sheet mask', b: 'sunscreen', tags: ['skincare'] },
    { id: 'asian-american-020', a: 'spam musubi', b: 'onigiri', tags: ['food'] },
    { id: 'asian-american-021', a: 'lazy susan', b: 'family style', tags: ['dining'] },
    { id: 'asian-american-022', a: 'costco', b: 'ranch 99', tags: ['shopping'] },
    { id: 'asian-american-023', a: 'gua sha', b: 'jade roller', tags: ['skincare'] },
    { id: 'asian-american-024', a: 'mochi', b: 'taiyaki', tags: ['dessert'] },
    { id: 'asian-american-025', a: 'soju', b: 'sake', tags: ['drinks'] },
    { id: 'asian-american-026', a: 'night market', b: 'food hall', tags: ['food'] },
    { id: 'asian-american-027', a: 'egg tart', b: 'pineapple bun', tags: ['bakery'] },
    { id: 'asian-american-028', a: 'sunday temple', b: 'sunday church', tags: ['weekend'] },
    { id: 'asian-american-029', a: 'jasmine rice', b: 'sticky rice', tags: ['staples'] },
    { id: 'asian-american-030', a: 'claw machine', b: 'gacha', tags: ['arcade'] },
    { id: 'asian-american-031', a: 'kimchi', b: 'pickled radish', tags: ['sides'] },
    { id: 'asian-american-032', a: 'dumplings', b: 'potstickers', tags: ['food'] },
    { id: 'asian-american-033', a: 'family group chat', b: 'wechat', tags: ['messaging'] },
    { id: 'asian-american-034', a: 'sun cake', b: 'moon cake', tags: ['pastry'] },
    { id: 'asian-american-035', a: 'k-drama', b: 'c-drama', tags: ['tv'] },
    { id: 'asian-american-036', a: 'milk tea', b: 'grass jelly', tags: ['drinks'] },
    { id: 'asian-american-037', a: 'lucky bamboo', b: 'orchid', tags: ['plants'] },
    { id: 'asian-american-038', a: 'water bottle after meal', b: 'hot water', tags: ['habits'] },
    { id: 'asian-american-039', a: 'gold jewelry', b: 'jade bracelet', tags: ['heirlooms'] },
    { id: 'asian-american-040', a: 'zongzi', b: 'tamale', tags: ['wrapped-food'] },
    { id: 'asian-american-041', a: 'century egg', b: 'salted egg', tags: ['food'] },
    { id: 'asian-american-042', a: 'longevity noodles', b: 'birthday cake', tags: ['birthday'] },
  ],
}
