import type { WordPack } from '../types'
import { buildPairs, type PairGroup, type PairSeed } from './build'

/**
 * Food and Going Out: restaurant, bar, hosting, and weekend-plan vocabulary.
 */
const seeds = [
  ["tacos", "burritos", ["mexican"]],
  ["pizza", "flatbread", ["food"]],
  ["ramen shop", "noodle bar", ["noodles"]],
  ["sushi", "poke", ["seafood"]],
  ["burger", "sandwich", ["food"]],
  ["cocktail", "mocktail", ["drinks"]],
  ["brunch", "happy hour", ["plans"]],
  ["reservation", "walk-in", ["restaurants"]],
  ["small plates", "tasting menu", ["restaurants"]],
  ["food truck", "pop-up", ["restaurants"]],
  ["wine bar", "brewery", ["drinks"]],
  ["speakeasy", "dive bar", ["nightlife"]],
  ["farmers market", "grocery store", ["shopping"]],
  ["charcuterie", "cheese board", ["hosting"]],
  ["potluck", "dinner party", ["hosting"]],
  ["delivery", "takeout", ["food"]],
  ["omakase", "prix fixe", ["restaurants"]],
  ["dim sum", "tapas", ["shared"]],
  ["ice cream", "gelato", ["dessert"]],
  ["donuts", "cupcakes", ["dessert"]],
  ["espresso martini", "negroni", ["cocktails"]],
  ["mezcal", "tequila", ["spirits"]],
  ["natural wine", "orange wine", ["drinks"]],
  ["beer flight", "wine tasting", ["drinks"]],
  ["karaoke bar", "arcade bar", ["nightlife"]],
  ["coffee date", "lunch date", ["dating"]],
  ["outdoor patio", "rooftop", ["restaurants"]],
  ["food hall", "hawker center", ["food"]],
  ["late-night fries", "late-night pizza", ["late-night"]],
  ["split the bill", "venmo request", ["payment"]],
  ["host gift", "thank-you text", ["hosting"]],
  ["leftovers", "doggie bag", ["food"]],
  ["birthday dinner", "anniversary dinner", ["plans"]],
  ["chef counter", "bar seating", ["restaurants"]],
  ["menu special", "daily special", ["restaurants"]],
  ["waitlist", "reservation deposit", ["restaurants"]],
  ["sparkling water", "still water", ["drinks"]],
  ["last call", "closing tab", ["nightlife"]],
] as const satisfies readonly PairSeed[]

const groups = [
  {
    tag: "restaurants",
    terms: [
    "reservation",
    "walk-in",
    "waitlist",
    "bar seating",
    "chef counter",
    "communal table",
    "booth",
    "patio table",
    "rooftop table",
    "private room",
    "prix fixe",
    "tasting menu",
    "omakase",
    "a la carte",
    "daily special",
    "happy hour menu",
    "late-night menu",
    "brunch menu",
    "kids menu",
    "dessert menu",
    "wine list",
    "bill folder",
    ],
  },
  {
    tag: "cuisines",
    terms: [
    "tacos",
    "burritos",
    "quesadilla",
    "arepa",
    "empanada",
    "pupusa",
    "sushi",
    "poke bowl",
    "ramen bowl",
    "udon",
    "pho",
    "banh mi",
    "thai curry",
    "pad thai",
    "bibimbap",
    "korean bbq",
    "hot pot",
    "dim sum",
    "bao",
    "dumplings",
    "shawarma",
    "falafel",
    ],
  },
  {
    tag: "comfort",
    terms: [
    "burger",
    "fried chicken",
    "chicken sandwich",
    "grilled cheese",
    "mac and cheese",
    "pizza",
    "flatbread",
    "pasta",
    "lasagna",
    "meatballs",
    "caesar salad",
    "cobb salad",
    "soup dumplings",
    "wonton soup",
    "clam chowder",
    "chili",
    "bbq ribs",
    "brisket",
    "pulled pork",
    "loaded fries",
    "nachos",
    "wings",
    ],
  },
  {
    tag: "dessert",
    terms: [
    "ice cream",
    "gelato",
    "soft serve",
    "frozen yogurt",
    "shaved ice",
    "snow cone",
    "halo-halo",
    "bingsu",
    "milkshake",
    "brownie",
    "cookie skillet",
    "cupcake",
    "donut",
    "croissant",
    "cinnamon roll",
    "cheesecake",
    "tiramisu",
    "creme brulee",
    "flan",
    "mango sticky rice",
    "mochi",
    "dango",
    "taiyaki",
    "churros",
    ],
  },
  {
    tag: "drinks",
    terms: [
    "sparkling water",
    "still water",
    "iced tea",
    "lemonade",
    "cold brew",
    "espresso",
    "cappuccino",
    "matcha latte",
    "chai latte",
    "smoothie",
    "fresh juice",
    "kombucha",
    "mocktail",
    "cocktail",
    "highball",
    "negroni",
    "old fashioned",
    "espresso martini",
    "margarita",
    "paloma",
    "aperol spritz",
    "nightcap",
    ],
  },
  {
    tag: "bars",
    terms: [
    "dive bar",
    "sports bar",
    "wine bar",
    "cocktail bar",
    "speakeasy",
    "brewery",
    "taproom",
    "beer garden",
    "rooftop bar",
    "hotel bar",
    "karaoke bar",
    "arcade bar",
    "piano bar",
    "jazz club",
    "comedy club",
    "dance floor",
    "bottle service",
    "cover charge",
    "last call",
    "closing tab",
    "bar crawl",
    "designated driver",
    ],
  },
  {
    tag: "hosting",
    terms: [
    "potluck",
    "dinner party",
    "game night",
    "watch party",
    "bbq",
    "picnic",
    "housewarming",
    "birthday dinner",
    "holiday dinner",
    "friendsgiving",
    "charcuterie board",
    "cheese board",
    "crudite platter",
    "chips and dip",
    "homemade dessert",
    "signature cocktail",
    "host gift",
    "place cards",
    "serving platter",
    "leftovers",
    "thank-you text",
    "dish duty",
    ],
  },
  {
    tag: "logistics",
    terms: [
    "group text",
    "reservation link",
    "calendar invite",
    "poll for dates",
    "headcount",
    "plus one",
    "dietary restrictions",
    "allergy note",
    "vegetarian option",
    "vegan option",
    "gluten-free option",
    "split the bill",
    "venmo request",
    "service fee",
    "tip jar",
    "corkage fee",
    "cake cutting fee",
    "parking validation",
    "rideshare pickup",
    "coat check",
    "lost card",
    "receipt photo",
    ],
  },
  {
    tag: "plans",
    terms: [
    "coffee date",
    "lunch date",
    "brunch",
    "happy hour",
    "early dinner",
    "late dinner",
    "dessert run",
    "boba run",
    "dessert run",
    "night market",
    "food court",
    "farmers market",
    "food truck park",
    "pop-up dinner",
    "supper club",
    "wine tasting",
    "beer flight",
    "cooking class",
    "baking class",
    "picnic date",
    "double date",
    "afterparty",
    "nightcap",
    ],
  },
  {
    tag: "kitchen",
    terms: [
    "cutting board",
    "chef knife",
    "mixing bowl",
    "measuring cup",
    "whisk",
    "spatula",
    "tongs",
    "sheet pan",
    "dutch oven",
    "cast iron pan",
    "wok",
    "steamer basket",
    "rice cooker",
    "pressure cooker",
    "instant pot",
    "air fryer",
    "blender",
    "food processor",
    "stand mixer",
    "immersion blender",
    "kitchen timer",
    "dish towel",
    "apron",
    ],
  },
  {
    tag: "shopping",
    terms: [
    "grocery list",
    "farmers market",
    "butcher counter",
    "fish counter",
    "bakery case",
    "cheese counter",
    "wine shop",
    "liquor store",
    "specialty grocer",
    "bulk bins",
    "produce aisle",
    "spice aisle",
    "frozen aisle",
    "snack aisle",
    "checkout line",
    "reusable bag",
    "paper bag",
    "receipt",
    "loyalty card",
    "coupon",
    "sample station",
    "rotisserie chicken",
    ],
  },
  {
    tag: "taste",
    terms: [
    "sweet",
    "salty",
    "sour",
    "bitter",
    "umami",
    "spicy",
    "smoky",
    "tangy",
    "creamy",
    "crunchy",
    "crispy",
    "chewy",
    "flaky",
    "buttery",
    "garlicky",
    "herby",
    "citrusy",
    "peppery",
    "fermented",
    "pickled",
    "charred",
    "toasty",
    ],
  },
] as const satisfies readonly PairGroup[]

export const foodGoingOut: WordPack = {
  id: "food-going-out",
  name: "Food & Going Out",
  description: "Restaurants, drinks, hosting, and city-night plans for social groups.",
  builtIn: true,
  pairs: buildPairs("food-going-out", seeds, groups, 250),
}
