import type { WordPack } from '../types'
import { buildPairs, type PairSeed } from './build'

/**
 * Food and Going Out: restaurant, bar, hosting, and weekend-plan vocabulary.
 */
const seeds = [
  // Latin and Mediterranean dishes
  ["taco", "gyro", ["handheld"]],
  ["quesadilla", "enchilada", ["latin"]],
  ["burrito", "enchilada", ["latin"]],
  ["quesadilla", "nachos", ["latin"]],
  ["guacamole", "hummus", ["dips"]],
  ["tamale", "empanada", ["latin"]],
  ["corn tortilla", "flour tortilla", ["latin"]],
  ["churro", "funnel cake", ["dessert"]],
  ["tres leches", "rum cake", ["dessert"]],
  ["horchata", "thai tea", ["drinks"]],
  ["ceviche", "poke", ["seafood"]],
  ["plantain", "yuca", ["sides"]],
  ["tequila", "mezcal", ["spirits"]],
  ["margarita", "paloma", ["cocktails"]],
  ["mojito", "margarita", ["cocktails"]],
  ["gyro", "shawarma", ["mediterranean"]],
  ["falafel", "pakora", ["fritters"]],
  ["hummus", "baba ganoush", ["dips"]],
  ["pita", "naan", ["bread"]],
  ["couscous", "quinoa", ["grains"]],
  ["kebab", "satay", ["skewers"]],
  ["paella", "jambalaya", ["rice"]],
  ["risotto", "paella", ["rice"]],
  ["moussaka", "lasagna", ["baked"]],
  ["baklava", "cannoli", ["pastry"]],

  // East and Southeast Asian dishes
  ["sushi", "sashimi", ["japanese"]],
  ["sushi", "poke", ["seafood"]],
  ["ramen", "wonton soup", ["noodles"]],
  ["ramen", "lo mein", ["noodles"]],
  ["udon", "lo mein", ["noodles"]],
  ["pho", "udon", ["noodles"]],
  ["dumpling", "wonton", ["dumplings"]],
  ["bao", "dumpling", ["dumplings"]],
  ["siu mai", "soup dumpling", ["dim sum"]],
  ["spring roll", "summer roll", ["rolls"]],
  ["bibimbap", "poke bowl", ["rice"]],
  ["congee", "grits", ["porridge"]],
  ["hot pot", "fondue", ["shared"]],
  ["hot pot", "korean bbq", ["shared"]],
  ["bulgogi", "beef teriyaki", ["grilled"]],
  ["kimchi", "pickles", ["pickled"]],
  ["miso soup", "egg drop soup", ["soup"]],
  ["pad thai", "drunken noodles", ["noodles"]],
  ["green curry", "massaman curry", ["curry"]],
  ["mapo tofu", "kung pao chicken", ["chinese"]],
  ["banh mi", "hoagie", ["sandwiches"]],
  ["bubble tea", "milk tea", ["drinks"]],
  ["matcha", "chai", ["tea"]],
  ["mochi", "dango", ["dessert"]],
  ["bingsu", "shaved ice", ["dessert"]],

  // Proteins, cheeses, and South Asian dishes
  ["naan", "roti", ["bread"]],
  ["samosa", "empanada", ["pastry"]],
  ["pakora", "tempura", ["fried"]],
  ["tikka masala", "korma", ["curry"]],
  ["biryani", "pilaf", ["rice"]],
  ["chutney", "relish", ["condiments"]],
  ["raita", "tzatziki", ["yogurt"]],
  ["curry", "stew", ["saucy"]],
  ["kebab", "meatball", ["meat"]],
  ["lentils", "chickpeas", ["legumes"]],
  ["tempeh", "seitan", ["plant protein"]],
  ["tahini", "peanut butter", ["spreads"]],
  ["feta", "goat cheese", ["cheese"]],
  ["mozzarella", "burrata", ["cheese"]],
  ["parmesan", "pecorino", ["cheese"]],
  ["cheddar", "gouda", ["cheese"]],
  ["brie", "camembert", ["cheese"]],
  ["salami", "prosciutto", ["cured meat"]],
  ["sausage", "chorizo", ["sausage"]],
  ["bacon", "pancetta", ["cured meat"]],
  ["smoked salmon", "smoked trout", ["seafood"]],
  ["lobster", "shrimp", ["shellfish"]],
  ["shrimp", "scallops", ["shellfish"]],
  ["tuna", "swordfish", ["fish"]],
  ["oyster", "mussel", ["shellfish"]],

  // Italian and American comfort food
  ["burger", "chicken sandwich", ["sandwiches"]],
  ["burger", "sloppy joe", ["sandwiches"]],
  ["hot dog", "corn dog", ["fair food"]],
  ["focaccia", "ciabatta", ["bread"]],
  ["pizza", "calzone", ["italian"]],
  ["calzone", "stromboli", ["italian"]],
  ["spaghetti", "linguine", ["pasta"]],
  ["ravioli", "tortellini", ["pasta"]],
  ["lasagna", "baked ziti", ["pasta"]],
  ["marinara", "pesto", ["sauce"]],
  ["alfredo", "carbonara", ["pasta"]],
  ["meatball", "sausage", ["meat"]],
  ["risotto", "polenta", ["italian"]],
  ["gnocchi", "ravioli", ["pasta"]],
  ["garlic bread", "breadsticks", ["bread"]],
  ["grilled cheese", "patty melt", ["sandwiches"]],
  ["mac and cheese", "baked ziti", ["baked"]],
  ["fried chicken", "chicken wings", ["chicken"]],
  ["chicken tenders", "fish sticks", ["breaded"]],
  ["wings", "ribs", ["barbecue"]],
  ["brisket", "pulled pork", ["barbecue"]],
  ["meatloaf", "pot roast", ["comfort"]],
  ["chili", "stew", ["soup"]],
  ["chowder", "bisque", ["soup"]],
  ["caesar salad", "cobb salad", ["salad"]],

  // Breakfast and bakery
  ["pancake", "waffle", ["breakfast"]],
  ["pancake", "french toast", ["breakfast"]],
  ["omelet", "frittata", ["eggs"]],
  ["omelet", "fried eggs", ["eggs"]],
  ["sausage", "ham", ["breakfast"]],
  ["hash browns", "home fries", ["potatoes"]],
  ["english muffin", "toast", ["breakfast"]],
  ["toast", "biscuit", ["bread"]],
  ["cereal", "granola", ["breakfast"]],
  ["oatmeal", "grits", ["porridge"]],
  ["yogurt", "cottage cheese", ["dairy"]],
  ["yogurt parfait", "acai bowl", ["breakfast"]],
  ["muffin", "danish", ["bakery"]],
  ["croissant", "danish", ["pastry"]],
  ["donut", "croissant", ["bakery"]],
  ["danish", "turnover", ["pastry"]],
  ["baguette", "ciabatta", ["bread"]],
  ["sourdough", "rye", ["bread"]],
  ["biscuit", "scone", ["bakery"]],
  ["jam", "marmalade", ["spreads"]],
  ["honey", "agave", ["sweeteners"]],
  ["peanut butter", "almond butter", ["spreads"]],
  ["cream cheese", "butter", ["spreads"]],
  ["cappuccino", "hot chocolate", ["drinks"]],
  ["latte", "cappuccino", ["coffee"]],

  // Desserts and candy
  ["ice cream", "gelato", ["dessert"]],
  ["frozen yogurt", "sorbet", ["dessert"]],
  ["gelato", "sorbet", ["dessert"]],
  ["soft serve", "custard", ["dessert"]],
  ["milkshake", "root beer float", ["dessert"]],
  ["brownie", "cupcake", ["baked"]],
  ["brownie", "blondie", ["baked"]],
  ["cupcake", "muffin", ["baked"]],
  ["layer cake", "sheet cake", ["cake"]],
  ["cheesecake", "tiramisu", ["dessert"]],
  ["cheesecake", "key lime pie", ["dessert"]],
  ["creme brulee", "flan", ["custard"]],
  ["pudding", "custard", ["dessert"]],
  ["rice pudding", "tapioca", ["pudding"]],
  ["apple pie", "peach cobbler", ["fruit dessert"]],
  ["pie", "tart", ["pastry"]],
  ["cobbler", "crumble", ["fruit dessert"]],
  ["biscotti", "shortbread", ["cookies"]],
  ["macaron", "meringue", ["dessert"]],
  ["donut", "fritter", ["fried"]],
  ["churro", "donut", ["fried"]],
  ["cinnamon roll", "sticky bun", ["bakery"]],
  ["caramel", "toffee", ["candy"]],
  ["fudge", "truffle", ["chocolate"]],
  ["gummy bears", "jelly beans", ["candy"]],

  // Produce and herbs
  ["apple", "plum", ["fruit"]],
  ["peach", "nectarine", ["fruit"]],
  ["grapefruit", "tangerine", ["citrus"]],
  ["lemon", "grapefruit", ["citrus"]],
  ["strawberry", "cherry", ["fruit"]],
  ["blueberry", "grape", ["fruit"]],
  ["cantaloupe", "honeydew", ["melon"]],
  ["mango", "peach", ["fruit"]],
  ["pineapple", "papaya", ["tropical fruit"]],
  ["cherry", "cranberry", ["fruit"]],
  ["kiwi", "dragon fruit", ["fruit"]],
  ["banana", "plantain", ["fruit"]],
  ["carrot", "parsnip", ["root vegetables"]],
  ["asparagus", "green beans", ["vegetables"]],
  ["spinach", "kale", ["greens"]],
  ["lettuce", "cabbage", ["greens"]],
  ["cucumber", "celery", ["vegetables"]],
  ["eggplant", "bell pepper", ["vegetables"]],
  ["potato", "parsnip", ["root vegetables"]],
  ["onion", "shallot", ["alliums"]],
  ["garlic", "ginger", ["aromatics"]],
  ["cilantro", "parsley", ["herbs"]],
  ["basil", "mint", ["herbs"]],
  ["rosemary", "thyme", ["herbs"]],
  ["tomato", "tomatillo", ["produce"]],

  // Coffee, soft drinks, beer, wine, and cocktails
  ["espresso", "americano", ["coffee"]],
  ["cold brew", "iced coffee", ["coffee"]],
  ["green tea", "black tea", ["tea"]],
  ["iced tea", "fruit punch", ["soft drinks"]],
  ["lemonade", "limeade", ["soft drinks"]],
  ["orange juice", "apple juice", ["juice"]],
  ["smoothie", "fresh juice", ["drinks"]],
  ["sparkling water", "tonic water", ["carbonated"]],
  ["cola", "root beer", ["soda"]],
  ["ginger ale", "tonic water", ["mixers"]],
  ["hot chocolate", "mocha", ["hot drinks"]],
  ["milk", "oat milk", ["milk"]],
  ["coconut water", "sports drink", ["hydration"]],
  ["beer", "cider", ["alcohol"]],
  ["ale", "lager", ["beer"]],
  ["stout", "lager", ["beer"]],
  ["ipa", "pilsner", ["beer"]],
  ["red wine", "white wine", ["wine"]],
  ["rose", "sparkling wine", ["wine"]],
  ["champagne", "prosecco", ["wine"]],
  ["sangria", "mimosa", ["wine cocktails"]],
  ["mimosa", "bellini", ["brunch drinks"]],
  ["cocktail", "mocktail", ["drinks"]],
  ["martini", "manhattan", ["cocktails"]],
  ["negroni", "old fashioned", ["cocktails"]],

  // Bars, restaurants, and other places to go
  ["margarita", "daiquiri", ["cocktails"]],
  ["moscow mule", "dark and stormy", ["cocktails"]],
  ["gin", "vodka", ["spirits"]],
  ["bourbon", "scotch", ["whiskey"]],
  ["sake", "plum wine", ["spirits"]],
  ["wine", "cider", ["alcohol"]],
  ["brewery", "winery", ["venues"]],
  ["taproom", "beer garden", ["venues"]],
  ["diner", "cafeteria", ["restaurants"]],
  ["cafe", "bakery", ["restaurants"]],
  ["diner", "bistro", ["restaurants"]],
  ["food truck", "food cart", ["street food"]],
  ["food court", "food hall", ["restaurants"]],
  ["night market", "farmers market", ["markets"]],
  ["pub", "sports bar", ["venues"]],
  ["dive bar", "sports bar", ["bars"]],
  ["wine bar", "cocktail bar", ["bars"]],
  ["rooftop bar", "hotel bar", ["bars"]],
  ["speakeasy", "dive bar", ["bars"]],
  ["karaoke bar", "arcade bar", ["bars"]],
  ["jazz club", "comedy club", ["nightlife"]],
  ["steakhouse", "seafood restaurant", ["restaurants"]],
  ["pizzeria", "burger joint", ["restaurants"]],
  ["ice cream shop", "boba shop", ["dessert shops"]],
  ["coffee shop", "boba shop", ["cafes"]],

  // Dining and social activities
  ["bakery", "butcher", ["food shops"]],
  ["buffet", "cafeteria", ["self service"]],
  ["patio", "dining room", ["seating"]],
  ["booth", "counter", ["seating"]],
  ["bowling", "karaoke", ["activities"]],
  ["karaoke", "trivia", ["activities"]],
  ["concert", "comedy show", ["shows"]],
  ["dancing", "karaoke", ["nightlife"]],
  ["lunch", "dinner", ["meals"]],
  ["breakfast", "brunch", ["meals"]],
  ["counter service", "table service", ["ordering"]],
  ["dine-in", "takeout", ["ordering"]],
  ["reservation", "walk-in", ["restaurants"]],
  ["potluck", "dinner party", ["hosting"]],
  ["picnic", "tailgate", ["outdoors"]],
  ["wine tasting", "beer tasting", ["tastings"]],
  ["cooking class", "mixology class", ["classes"]],
  ["grilling", "baking", ["cooking"]],
  ["roasting", "braising", ["cooking"]],
  ["sauteing", "stir-frying", ["cooking"]],
  ["steaming", "boiling", ["cooking"]],
  ["chopping", "dicing", ["cooking"]],
  ["whisking", "stirring", ["cooking"]],
  ["sipping", "gulping", ["drinking"]],
  ["snacking", "feasting", ["eating"]],
] as const satisfies readonly PairSeed[]

export const foodGoingOut: WordPack = {
  id: "food-going-out",
  name: "Food & Going Out",
  description: "Restaurants, drinks, hosting, and city-night plans for social groups.",
  builtIn: true,
  pairs: buildPairs("food-going-out", seeds, [], 250),
}
