import type { WordPack } from '../types'

/**
 * Food & Going Out: eating, drinking, and where the group hangs.
 */
export const foodGoingOut: WordPack = {
  id: 'food-going-out',
  name: 'Food & Going Out',
  description: 'Eating, drinking, and where the group actually hangs out.',
  builtIn: true,
  pairs: [
    { id: 'food-going-out-001', a: 'boba', b: 'matcha latte', tags: ['drinks'] },
    { id: 'food-going-out-002', a: 'costco', b: 'trader joe\'s', tags: ['grocery'] },
    { id: 'food-going-out-003', a: 'dim sum', b: 'hot pot', tags: ['dining'] },
    { id: 'food-going-out-004', a: 'brunch', b: 'happy hour', tags: ['occasions'] },
    { id: 'food-going-out-005', a: 'taco truck', b: 'food hall', tags: ['casual'] },
    { id: 'food-going-out-006', a: 'natural wine', b: 'craft beer', tags: ['drinks'] },
    { id: 'food-going-out-007', a: 'omakase', b: 'tasting menu', tags: ['fancy'] },
    { id: 'food-going-out-008', a: 'espresso martini', b: 'old fashioned', tags: ['cocktails'] },
    { id: 'food-going-out-009', a: 'ramen shop', b: 'noodle bar', tags: ['dining'] },
    { id: 'food-going-out-010', a: 'wine bar', b: 'cocktail lounge', tags: ['nightlife'] },
    { id: 'food-going-out-011', a: 'brewery', b: 'distillery', tags: ['drinks'] },
    { id: 'food-going-out-012', a: 'street food', b: 'pop-up', tags: ['casual'] },
    { id: 'food-going-out-013', a: 'smash burger', b: 'fried chicken sandwich', tags: ['food'] },
    { id: 'food-going-out-014', a: 'iced coffee', b: 'cold brew', tags: ['coffee'] },
    { id: 'food-going-out-015', a: 'sushi', b: 'poke', tags: ['food'] },
    { id: 'food-going-out-016', a: 'pizza slice', b: 'calzone', tags: ['food'] },
    { id: 'food-going-out-017', a: 'farmers market', b: 'flea market', tags: ['markets'] },
    { id: 'food-going-out-018', a: 'diner', b: 'coffee shop', tags: ['casual'] },
    { id: 'food-going-out-019', a: 'reservation', b: 'walk-in', tags: ['dining-logistics'] },
    { id: 'food-going-out-020', a: 'birthday dinner', b: 'date night', tags: ['occasions'] },
    { id: 'food-going-out-021', a: 'appetizer', b: 'side dish', tags: ['courses'] },
    { id: 'food-going-out-022', a: 'ice cream', b: 'gelato', tags: ['dessert'] },
    { id: 'food-going-out-023', a: 'bakery', b: 'donut shop', tags: ['sweets'] },
    { id: 'food-going-out-024', a: 'rooftop bar', b: 'beer garden', tags: ['nightlife'] },
    { id: 'food-going-out-025', a: 'potluck', b: 'dinner party', tags: ['home'] },
    { id: 'food-going-out-026', a: 'takeout', b: 'delivery', tags: ['at-home'] },
    { id: 'food-going-out-027', a: 'tapas', b: 'mezze', tags: ['sharing'] },
    { id: 'food-going-out-028', a: 'buffet', b: 'all you can eat', tags: ['dining'] },
    { id: 'food-going-out-029', a: 'brunch cocktail', b: 'mimosa', tags: ['drinks'] },
    { id: 'food-going-out-030', a: 'food coma', b: 'sugar rush', tags: ['aftermath'] },
    { id: 'food-going-out-031', a: 'hole in the wall', b: 'michelin star', tags: ['restaurants'] },
    { id: 'food-going-out-032', a: 'aperol spritz', b: 'margarita', tags: ['cocktails'] },
    { id: 'food-going-out-033', a: 'oat milk', b: 'almond milk', tags: ['alt-milk'] },
    { id: 'food-going-out-034', a: 'charcuterie board', b: 'cheese plate', tags: ['snacks'] },
    { id: 'food-going-out-035', a: 'birria taco', b: 'korean corn dog', tags: ['viral-food'] },
    { id: 'food-going-out-036', a: 'happy hour oyster', b: 'raw bar', tags: ['seafood'] },
    { id: 'food-going-out-037', a: 'late night snack', b: 'midnight ramen', tags: ['late-night'] },
    { id: 'food-going-out-038', a: 'brunch line', b: 'waitlist', tags: ['waiting'] },
  ],
}
