import type { WordPack } from '../types'

/**
 * General Mix: broadly legible everyday pairs. Safe default for any group.
 */
export const generalMix: WordPack = {
  id: 'general-mix',
  name: 'General Mix',
  description: 'Everyday things everyone knows — a safe, broadly legible starter.',
  builtIn: true,
  pairs: [
    { id: 'general-mix-001', a: 'coffee', b: 'tea', tags: ['drinks'] },
    { id: 'general-mix-002', a: 'cat', b: 'dog', tags: ['animals'] },
    { id: 'general-mix-003', a: 'beach', b: 'lake', tags: ['places'] },
    { id: 'general-mix-004', a: 'umbrella', b: 'raincoat', tags: ['objects'] },
    { id: 'general-mix-005', a: 'pencil', b: 'pen', tags: ['objects'] },
    { id: 'general-mix-006', a: 'bicycle', b: 'scooter', tags: ['transport'] },
    { id: 'general-mix-007', a: 'mountain', b: 'hill', tags: ['nature'] },
    { id: 'general-mix-008', a: 'apple', b: 'pear', tags: ['fruit'] },
    { id: 'general-mix-009', a: 'summer', b: 'spring', tags: ['seasons'] },
    { id: 'general-mix-010', a: 'guitar', b: 'ukulele', tags: ['music'] },
    { id: 'general-mix-011', a: 'library', b: 'bookstore', tags: ['places'] },
    { id: 'general-mix-012', a: 'soap', b: 'shampoo', tags: ['bathroom'] },
    { id: 'general-mix-013', a: 'candle', b: 'lamp', tags: ['objects'] },
    { id: 'general-mix-014', a: 'blanket', b: 'towel', tags: ['objects'] },
    { id: 'general-mix-015', a: 'river', b: 'canal', tags: ['nature'] },
    { id: 'general-mix-016', a: 'sunglasses', b: 'reading glasses', tags: ['objects'] },
    { id: 'general-mix-017', a: 'hammer', b: 'wrench', tags: ['tools'] },
    { id: 'general-mix-018', a: 'necklace', b: 'bracelet', tags: ['jewelry'] },
    { id: 'general-mix-019', a: 'balloon', b: 'kite', tags: ['objects'] },
    { id: 'general-mix-020', a: 'clock', b: 'watch', tags: ['objects'] },
    { id: 'general-mix-021', a: 'sneakers', b: 'sandals', tags: ['clothes'] },
    { id: 'general-mix-022', a: 'backpack', b: 'tote bag', tags: ['objects'] },
    { id: 'general-mix-023', a: 'piano', b: 'keyboard', tags: ['music'] },
    { id: 'general-mix-024', a: 'garden', b: 'greenhouse', tags: ['places'] },
    { id: 'general-mix-025', a: 'snowman', b: 'scarecrow', tags: ['seasonal'] },
    { id: 'general-mix-026', a: 'wallet', b: 'purse', tags: ['objects'] },
    { id: 'general-mix-027', a: 'ferry', b: 'sailboat', tags: ['transport'] },
    { id: 'general-mix-028', a: 'firefighter', b: 'lifeguard', tags: ['jobs'] },
    { id: 'general-mix-029', a: 'butterfly', b: 'dragonfly', tags: ['animals'] },
    { id: 'general-mix-030', a: 'volcano', b: 'geyser', tags: ['nature'] },
    { id: 'general-mix-031', a: 'chess', b: 'checkers', tags: ['games'] },
    { id: 'general-mix-032', a: 'painting', b: 'photograph', tags: ['art'] },
    { id: 'general-mix-033', a: 'birthday', b: 'anniversary', tags: ['occasions'] },
    { id: 'general-mix-034', a: 'whisper', b: 'mumble', tags: ['actions'] },
    { id: 'general-mix-035', a: 'stapler', b: 'tape dispenser', tags: ['office'] },
    { id: 'general-mix-036', a: 'globe', b: 'map', tags: ['objects'] },
    { id: 'general-mix-037', a: 'telescope', b: 'binoculars', tags: ['objects'] },
    { id: 'general-mix-038', a: 'mailbox', b: 'front door', tags: ['home'] },
    { id: 'general-mix-039', a: 'campfire', b: 'fireplace', tags: ['objects'] },
    { id: 'general-mix-040', a: 'escalator', b: 'elevator', tags: ['objects'] },
    { id: 'general-mix-041', a: 'lighthouse', b: 'water tower', tags: ['structures'] },
    { id: 'general-mix-042', a: 'raincheck', b: 'rsvp', tags: ['social'] },
    { id: 'general-mix-043', a: 'roommate', b: 'neighbor', tags: ['people'] },
    { id: 'general-mix-044', a: 'passport', b: 'driver license', tags: ['documents'] },
    { id: 'general-mix-045', a: 'suitcase', b: 'duffel bag', tags: ['travel'] },
    { id: 'general-mix-046', a: 'hiking', b: 'camping', tags: ['activities'] },
    { id: 'general-mix-047', a: 'aquarium', b: 'zoo', tags: ['places'] },
  ],
}
