import type { WordPack } from '../types'
import { buildPairs, type PairSeed } from './build'

/**
 * General Mix: broadly legible everyday pairs. Safe default for any group.
 *
 * Every matchup is explicit so additions are reviewed as complete rounds rather
 * than introduced indirectly through category-chain adjacency.
 */
const seeds = [
  ['coffee', 'hot chocolate', ['drinks']],
  ['milk', 'juice', ['drinks']],
  ['lemonade', 'fruit punch', ['drinks']],
  ['soda', 'juice', ['drinks']],
  ['smoothie', 'milkshake', ['drinks']],
  ['hot chocolate', 'apple cider', ['drinks']],
  ['beer', 'wine', ['drinks']],
  ['martini', 'margarita', ['drinks']],
  ['bottle', 'can', ['containers']],
  ['mug', 'glass', ['containers']],
  ['fork', 'spoon', ['tableware']],
  ['plate', 'bowl', ['tableware']],
  ['salt', 'pepper', ['seasonings']],
  ['ketchup', 'mustard', ['condiments']],
  ['butter', 'jam', ['spreads']],
  ['honey', 'jam', ['spreads']],
  ['bread', 'tortilla', ['food']],
  ['bagel', 'toast', ['breakfast']],
  ['pancakes', 'waffles', ['breakfast']],
  ['cereal', 'oatmeal', ['breakfast']],
  ['scrambled eggs', 'fried eggs', ['breakfast']],
  ['bacon', 'ham', ['breakfast']],
  ['muffin', 'brownie', ['baked goods']],
  ['cookie', 'cupcake', ['desserts']],
  ['cake', 'pie', ['desserts']],
  ['donut', 'bagel', ['baked goods']],
  ['ice cream', 'frozen yogurt', ['desserts']],
  ['popsicle', 'ice cream cone', ['desserts']],
  ['chocolate', 'vanilla', ['flavors']],
  ['apple', 'peach', ['fruit']],
  ['orange', 'tangerine', ['fruit']],
  ['lemon', 'orange', ['fruit']],
  ['peach', 'plum', ['fruit']],
  ['strawberry', 'blueberry', ['fruit']],
  ['blueberry', 'cranberry', ['fruit']],
  ['watermelon', 'pineapple', ['fruit']],
  ['mango', 'pineapple', ['fruit']],
  ['carrot', 'celery', ['vegetables']],
  ['broccoli', 'asparagus', ['vegetables']],
  ['spinach', 'lettuce', ['vegetables']],
  ['potato', 'carrot', ['vegetables']],
  ['onion', 'garlic', ['vegetables']],
  ['tomato', 'cucumber', ['vegetables']],
  ['zucchini', 'eggplant', ['vegetables']],
  ['rice', 'pasta', ['food']],
  ['spaghetti', 'lasagna', ['food']],
  ['sandwich', 'wrap', ['food']],
  ['hamburger', 'hot dog', ['food']],
  ['pizza', 'taco', ['food']],
  ['taco', 'quesadilla', ['food']],
  ['soup', 'stew', ['food']],
  ['salad', 'coleslaw', ['food']],
  ['fries', 'onion rings', ['food']],
  ['popcorn', 'pretzel', ['snacks']],
  ['peanuts', 'cashews', ['snacks']],
  ['almonds', 'walnuts', ['snacks']],
  ['salsa', 'hummus', ['dips']],

  ['cat', 'dog', ['animals']],
  ['puppy', 'kitten', ['animals']],
  ['rabbit', 'guinea pig', ['animals']],
  ['hamster', 'mouse', ['animals']],
  ['parrot', 'crow', ['animals']],
  ['robin', 'seagull', ['animals']],
  ['duck', 'goose', ['animals']],
  ['chicken', 'turkey', ['animals']],
  ['eagle', 'hawk', ['animals']],
  ['butterfly', 'moth', ['animals']],
  ['bee', 'wasp', ['animals']],
  ['ant', 'cockroach', ['animals']],
  ['mosquito', 'fly', ['animals']],
  ['spider', 'scorpion', ['animals']],
  ['frog', 'toad', ['animals']],
  ['turtle', 'snail', ['animals']],
  ['snake', 'lizard', ['animals']],
  ['alligator', 'crocodile', ['animals']],
  ['dolphin', 'whale', ['animals']],
  ['seal', 'sea lion', ['animals']],
  ['octopus', 'squid', ['animals']],
  ['crab', 'shrimp', ['animals']],
  ['shark', 'stingray', ['animals']],
  ['salmon', 'tuna', ['animals']],
  ['lion', 'tiger', ['animals']],
  ['leopard', 'cheetah', ['animals']],
  ['elephant', 'rhinoceros', ['animals']],
  ['giraffe', 'zebra', ['animals']],
  ['horse', 'pony', ['animals']],
  ['donkey', 'horse', ['animals']],
  ['cow', 'buffalo', ['animals']],
  ['sheep', 'goat', ['animals']],
  ['pig', 'cow', ['animals']],
  ['deer', 'moose', ['animals']],
  ['brown bear', 'polar bear', ['animals']],
  ['wolf', 'dog', ['animals']],
  ['fox', 'wolf', ['animals']],
  ['camel', 'llama', ['animals']],
  ['mouse', 'rat', ['animals']],

  ['couch', 'armchair', ['home']],
  ['stool', 'bench', ['home']],
  ['bed', 'hammock', ['home']],
  ['blanket', 'quilt', ['home']],
  ['pillow', 'cushion', ['home']],
  ['towel', 'washcloth', ['bathroom']],
  ['curtains', 'blinds', ['home']],
  ['rug', 'carpet', ['home']],
  ['closet', 'cabinet', ['storage']],
  ['drawer', 'shelf', ['storage']],
  ['dresser', 'closet', ['storage']],
  ['basket', 'bin', ['storage']],
  ['broom', 'mop', ['cleaning']],
  ['vacuum', 'broom', ['cleaning']],
  ['sponge', 'rag', ['cleaning']],
  ['soap', 'shampoo', ['bathroom']],
  ['toothbrush', 'floss', ['bathroom']],
  ['bathtub', 'shower', ['bathroom']],
  ['sink', 'bathtub', ['bathroom']],
  ['hairbrush', 'comb', ['bathroom']],
  ['hair dryer', 'curling iron', ['bathroom']],
  ['razor', 'hair clippers', ['bathroom']],
  ['candle', 'flashlight', ['lighting']],
  ['lamp', 'flashlight', ['lighting']],
  ['fan', 'air conditioner', ['home']],
  ['heater', 'fireplace', ['home']],
  ['refrigerator', 'freezer', ['kitchen']],
  ['oven', 'microwave', ['kitchen']],
  ['stove', 'grill', ['cooking']],
  ['toaster', 'waffle iron', ['kitchen']],
  ['blender', 'juicer', ['kitchen']],
  ['kettle', 'coffee maker', ['kitchen']],
  ['pot', 'frying pan', ['kitchen']],
  ['baking sheet', 'frying pan', ['kitchen']],
  ['corkscrew', 'bottle opener', ['kitchen']],
  ['can opener', 'vegetable peeler', ['kitchen']],
  ['knife', 'scissors', ['tools']],
  ['hammer', 'wrench', ['tools']],
  ['screwdriver', 'drill', ['tools']],
  ['nails', 'screws', ['tools']],
  ['chain', 'rope', ['objects']],
  ['wallet', 'purse', ['accessories']],
  ['backpack', 'suitcase', ['bags']],
  ['tote bag', 'duffel bag', ['bags']],
  ['umbrella', 'raincoat', ['rain gear']],
  ['sunglasses', 'goggles', ['eyewear']],
  ['clock', 'watch', ['time']],
  ['alarm clock', 'timer', ['time']],
  ['television', 'radio', ['electronics']],
  ['headphones', 'earbuds', ['electronics']],
  ['remote control', 'game controller', ['electronics']],
  ['telescope', 'binoculars', ['optics']],
  ['flashlight', 'lantern', ['lighting']],
  ['battery', 'generator', ['electronics']],
  ['extension cord', 'power strip', ['electronics']],
  ['button', 'zipper', ['clothing']],
  ['necklace', 'bracelet', ['jewelry']],
  ['ring', 'earrings', ['jewelry']],
  ['beanie', 'sun hat', ['clothing']],
  ['gloves', 'mittens', ['clothing']],
  ['sneakers', 'sandals', ['clothing']],
  ['rain boots', 'snow boots', ['clothing']],
  ['shirt', 'sweater', ['clothing']],
  ['jeans', 'sweatpants', ['clothing']],
  ['swimsuit', 'wetsuit', ['clothing']],
  ['jacket', 'coat', ['clothing']],
  ['bathrobe', 'pajamas', ['clothing']],
  ['scarf', 'bandana', ['clothing']],

  ['car', 'truck', ['transport']],
  ['bus', 'train', ['transport']],
  ['bicycle', 'scooter', ['transport']],
  ['motorcycle', 'scooter', ['transport']],
  ['boat', 'raft', ['transport']],
  ['sailboat', 'rowboat', ['transport']],
  ['subway', 'bus', ['transport']],
  ['airplane', 'helicopter', ['transport']],
  ['taxi', 'limousine', ['transport']],
  ['ferry', 'cruise ship', ['transport']],

  ['guitar', 'piano', ['music']],
  ['piano', 'drums', ['music']],
  ['violin', 'cello', ['music']],
  ['trumpet', 'trombone', ['music']],
  ['drums', 'tambourine', ['music']],
  ['microphone', 'speaker', ['music']],
  ['singer', 'drummer', ['music']],
  ['concert', 'music festival', ['music']],
  ['skateboard', 'roller skates', ['recreation']],
  ['balloon', 'bubble', ['recreation']],

  ['beach', 'lake', ['places']],
  ['river', 'stream', ['nature']],
  ['pond', 'lake', ['nature']],
  ['island', 'continent', ['nature']],
  ['mountain', 'hill', ['nature']],
  ['canyon', 'valley', ['nature']],
  ['cave', 'tunnel', ['places']],
  ['forest', 'jungle', ['nature']],
  ['meadow', 'field', ['nature']],
  ['swamp', 'desert', ['nature']],
  ['creek', 'river', ['nature']],
  ['glacier', 'iceberg', ['nature']],
  ['volcano', 'geyser', ['nature']],
  ['playground', 'swimming pool', ['places']],
  ['zoo', 'aquarium', ['places']],
  ['museum', 'library', ['places']],
  ['library', 'bookstore', ['places']],
  ['movie theater', 'arcade', ['places']],
  ['stadium', 'arena', ['places']],
  ['bowling alley', 'arcade', ['places']],
  ['diner', 'food truck', ['places']],
  ['bakery', 'candy shop', ['places']],
  ['salon', 'barbershop', ['places']],
  ['hotel', 'motel', ['places']],
  ['cabin', 'cottage', ['places']],
  ['apartment', 'house', ['home']],
  ['porch', 'balcony', ['home']],
  ['sidewalk', 'boardwalk', ['places']],
  ['bridge', 'tunnel', ['structures']],
  ['highway', 'back road', ['travel']],
  ['sunny', 'cloudy', ['weather']],
  ['rain', 'snow', ['weather']],
  ['drizzle', 'downpour', ['weather']],
  ['thunderstorm', 'rainstorm', ['weather']],
  ['fog', 'cloud', ['weather']],
  ['breeze', 'gust', ['weather']],
  ['blizzard', 'thunderstorm', ['weather']],
  ['sunrise', 'sunset', ['nature']],
  ['spring', 'fall', ['seasons']],
  ['summer', 'winter', ['seasons']],

  ['hiking', 'camping', ['activities']],
  ['walking', 'jogging', ['activities']],
  ['swimming', 'surfing', ['activities']],
  ['skiing', 'snowboarding', ['activities']],
  ['ice skating', 'roller skating', ['activities']],
  ['cycling', 'skateboarding', ['activities']],
  ['basketball', 'volleyball', ['sports']],
  ['baseball', 'softball', ['sports']],
  ['soccer', 'hockey', ['sports']],
  ['tennis', 'badminton', ['sports']],
  ['tennis', 'ping-pong', ['sports']],
  ['darts', 'archery', ['sports']],
  ['chess', 'checkers', ['games']],
  ['playing cards', 'dominoes', ['games']],
  ['crossword', 'word search', ['games']],
  ['hide-and-seek', 'tag', ['games']],
  ['karaoke', 'lip-syncing', ['activities']],
  ['singing', 'humming', ['actions']],
  ['whisper', 'mumble', ['actions']],
  ['laugh', 'giggle', ['actions']],
  ['shout', 'scream', ['actions']],
  ['borrow', 'lend', ['actions']],
  ['push', 'pull', ['actions']],
  ['throw', 'catch', ['actions']],
  ['birthday', 'anniversary', ['occasions']],
  ['picnic', 'barbecue', ['occasions']],
] as const satisfies readonly PairSeed[]

export const generalMix: WordPack = {
  id: 'general-mix',
  name: 'General Mix',
  description: 'Everyday things everyone knows, now large enough to play as the default by itself.',
  builtIn: true,
  pairs: buildPairs('general-mix', seeds, [], 250),
}
