import type { WordPack } from '../types'
import { buildPairs, type PairSeed } from './build'

/**
 * Early 30s Internet: platforms, online culture, and familiar digital life.
 *
 * Keep these pairs explicit: broad generated groups made neighboring terms look
 * related without guaranteeing that they produced a fair Woody round.
 */
const seeds = [
  // Platforms and services
  ['instagram', 'tiktok', ['platforms']],
  ['instagram', 'snapchat', ['platforms']],
  ['tiktok', 'youtube shorts', ['platforms']],
  ['youtube', 'twitch', ['platforms']],
  ['reddit', 'discord', ['communities']],
  ['reddit', 'facebook group', ['communities']],
  ['twitter', 'threads', ['platforms']],
  ['twitter', 'bluesky', ['platforms']],
  ['facebook', 'instagram', ['platforms']],
  ['linkedin', 'twitter', ['platforms']],
  ['pinterest', 'tumblr', ['platforms']],
  ['letterboxd', 'goodreads', ['platforms']],
  ['spotify', 'apple music', ['music']],
  ['soundcloud', 'bandcamp', ['music']],
  ['substack', 'medium', ['publishing']],
  ['whatsapp', 'telegram', ['messaging']],
  ['signal', 'whatsapp', ['messaging']],
  ['instagram live', 'tiktok live', ['video']],
  ['venmo', 'zelle', ['payments']],
  ['cash app', 'paypal', ['payments']],

  // Messaging
  ['group chat', 'direct message', ['messaging']],
  ['text message', 'voice memo', ['messaging']],
  ['voice call', 'video call', ['messaging']],
  ['facetime', 'zoom', ['video']],
  ['typing bubble', 'read receipt', ['messaging']],
  ['reaction', 'sticker', ['messaging']],
  ['mute', 'snooze', ['messaging']],
  ['archive', 'delete', ['messaging']],
  ['pin', 'bookmark', ['actions']],
  ['reply', 'forward', ['messaging']],
  ['hashtag', 'mention', ['social']],
  ['dm', 'comment', ['social']],
  ['group text', 'discord server', ['messaging']],
  ['close friends', 'followers', ['audience']],
  ['online', 'offline', ['status']],
  ['seen', 'delivered', ['messaging']],
  ['notification', 'reminder', ['alerts']],
  ['push notification', 'email alert', ['alerts']],
  ['ringtone', 'text tone', ['alerts']],
  ['autocorrect', 'predictive text', ['messaging']],

  // Posts and media formats
  ['meme', 'reaction gif', ['content']],
  ['screenshot', 'screen recording', ['content']],
  ['photo carousel', 'single photo', ['content']],
  ['story', 'feed post', ['content']],
  ['instagram reel', 'tiktok video', ['video']],
  ['livestream', 'premiere', ['video']],
  ['podcast', 'video essay', ['media']],
  ['newsletter', 'blog', ['publishing']],
  ['vlog', 'podcast', ['media']],
  ['tutorial', 'demo', ['content']],
  ['review', 'ranking', ['content']],
  ['unboxing', 'haul', ['content']],
  ['reaction video', 'commentary video', ['video']],
  ['video essay', 'documentary', ['content']],
  ['trailer', 'sneak peek', ['video']],
  ['thumbnail', 'profile picture', ['content']],
  ['caption', 'comment', ['posting']],
  ['thread', 'blog post', ['publishing']],
  ['quote tweet', 'repost', ['sharing']],
  ['duet', 'stitch', ['tiktok']],
  ['poll', 'quiz', ['interactive']],
  ['ama', 'interview', ['interactive']],
  ['playlist', 'mixtape', ['music']],
  ['ebook', 'audiobook', ['media']],
  ['gif', 'sticker', ['content']],

  // Common online actions
  ['like', 'bookmark', ['actions']],
  ['send', 'repost', ['actions']],
  ['follow', 'subscribe', ['actions']],
  ['unfollow', 'unsubscribe', ['actions']],
  ['block', 'report', ['safety']],
  ['scroll', 'swipe', ['actions']],
  ['tap', 'click', ['actions']],
  ['upload', 'download', ['actions']],
  ['stream', 'download', ['media']],
  ['log in', 'log out', ['accounts']],
  ['log out', 'delete account', ['accounts']],
  ['search', 'browse', ['actions']],
  ['bookmark', 'save', ['actions']],
  ['copy', 'paste', ['actions']],
  ['crop', 'filter', ['editing']],
  ['zoom in', 'full screen', ['viewing']],
  ['draft', 'published post', ['posting']],
  ['publish', 'schedule', ['posting']],
  ['comment', 'reply', ['social']],
  ['skip', 'shuffle', ['music']],

  // Social identity and discourse
  ['sponsored post', 'banner ad', ['social']],
  ['clickbait', 'rage bait', ['content']],
  ['humblebrag', 'thirst trap', ['posting']],
  ['subtweet', 'vaguepost', ['posting']],
  ['soft launch', 'hard launch', ['posting']],
  ['lurker', 'poster', ['personas']],
  ['troll', 'reply guy', ['personas']],
  ['influencer', 'streamer', ['creators']],
  ['follower', 'subscriber', ['audience']],
  ['mutual', 'follower', ['audience']],
  ['online friend', 'real-life friend', ['audience']],
  ['verified account', 'fan account', ['accounts']],
  ['burner account', 'finsta', ['accounts']],
  ['bot account', 'spam account', ['accounts']],
  ['public account', 'private account', ['accounts']],
  ['bio', 'status message', ['identity']],
  ['username', 'display name', ['identity']],
  ['profile photo', 'cover photo', ['identity']],
  ['hashtag', 'keyword', ['discovery']],
  ['forum', 'chat room', ['communities']],

  // Browsing habits and settings
  ['doomscrolling', 'binge-watching', ['habits']],
  ['lurking', 'posting', ['habits']],
  ['browser tabs', 'app windows', ['clutter']],
  ['screen time', 'data usage', ['metrics']],
  ['airplane mode', 'do not disturb', ['settings']],
  ['focus mode', 'sleep mode', ['settings']],
  ['dark mode', 'light mode', ['settings']],
  ['private browsing', 'guest mode', ['privacy']],
  ['watch later', 'read later', ['saving']],
  ['autoplay', 'shuffle', ['media']],
  ['push notification', 'notification badge', ['alerts']],
  ['infinite scroll', 'autoplay', ['feeds']],
  ['ad blocker', 'pop-up blocker', ['browsing']],
  ['password reset', 'account recovery', ['security']],
  ['cache', 'cookies', ['browsing']],
  ['browser history', 'search history', ['privacy']],
  ['open tabs', 'saved bookmarks', ['browsing']],
  ['wi-fi', 'cellular data', ['connectivity']],
  ['low power mode', 'airplane mode', ['settings']],
  ['grocery delivery', 'restaurant delivery', ['habits']],

  // Familiar digital tools
  ['google docs', 'notion', ['tools']],
  ['canva', 'figma', ['tools']],
  ['zoom', 'microsoft teams', ['tools']],
  ['slack', 'discord', ['tools']],
  ['dropbox', 'google drive', ['storage']],
  ['icloud drive', 'google drive', ['storage']],
  ['spreadsheet', 'slide deck', ['tools']],
  ['gmail', 'outlook', ['email']],
  ['chatgpt', 'claude', ['ai']],
  ['siri', 'alexa', ['assistants']],
  ['google maps', 'waze', ['navigation']],
  ['chrome', 'safari', ['browsers']],
  ['firefox', 'chrome', ['browsers']],
  ['google search', 'bing', ['search']],
  ['grammar checker', 'spellchecker', ['writing']],
  ['password manager', 'authenticator app', ['security']],
  ['calendar', 'reminders', ['tools']],
  ['notes app', 'tasks app', ['tools']],
  ['qr code', 'barcode', ['codes']],
  ['link', 'attachment', ['sharing']],

  // Online and mobile games
  ['wordle', 'connections', ['games']],
  ['wordle', 'mini crossword', ['games']],
  ['mini crossword', 'sudoku', ['games']],
  ['spelling bee', 'wordle', ['games']],
  ['among us', 'fall guys', ['games']],
  ['minecraft', 'fortnite', ['games']],
  ['fortnite', 'apex legends', ['games']],
  ['valorant', 'overwatch', ['games']],
  ['league of legends', 'dota 2', ['games']],
  ['animal crossing', 'stardew valley', ['games']],
  ['zelda', 'pokemon', ['games']],
  ['pokemon go', 'mario kart tour', ['games']],
  ['mario kart', 'smash bros.', ['games']],
  ['jackbox', 'among us', ['games']],
  ['candy crush', 'angry birds', ['games']],
  ['roblox', 'minecraft', ['games']],
  ['the sims', 'animal crossing', ['games']],
  ['chess app', 'sudoku app', ['games']],
  ['trivia app', 'crossword app', ['games']],
  ['mobile game', 'console game', ['games']],
  ['speedrun', 'walkthrough', ['gaming']],
  ['daily challenge', 'weekly challenge', ['gaming']],
  ['co-op', 'competitive', ['gaming']],
  ['voice chat', 'text chat', ['gaming']],
  ['lag', 'glitch', ['gaming']],

  // Shopping and money
  ['amazon', 'target', ['shopping']],
  ['etsy', 'ebay', ['shopping']],
  ['craigslist', 'facebook marketplace', ['shopping']],
  ['depop', 'poshmark', ['shopping']],
  ['doordash', 'uber eats', ['delivery']],
  ['instacart', 'amazon fresh', ['delivery']],
  ['promo code', 'gift card', ['shopping']],
  ['shopping cart', 'wish list', ['shopping']],
  ['delivery app', 'rideshare app', ['apps']],
  ['same-day delivery', 'standard shipping', ['shipping']],
  ['tracking number', 'order number', ['shipping']],
  ['return', 'exchange', ['shopping']],
  ['free trial', 'freemium', ['subscriptions']],
  ['subscription', 'one-time purchase', ['payments']],
  ['patreon', 'kickstarter', ['funding']],
  ['gofundme', 'kickstarter', ['funding']],
  ['robinhood', 'coinbase', ['finance']],
  ['crypto wallet', 'digital wallet', ['payments']],
  ['apple pay', 'google pay', ['payments']],
  ['autopay', 'manual payment', ['payments']],

  // Privacy and security
  ['password', 'passcode', ['security']],
  ['passcode', 'face id', ['security']],
  ['face id', 'fingerprint', ['security']],
  ['two-factor code', 'security question', ['security']],
  ['spam', 'phishing', ['security']],
  ['scammer', 'catfish', ['security']],
  ['hacker', 'scammer', ['security']],
  ['spyware', 'ransomware', ['security']],
  ['fake alert', 'phishing email', ['security']],
  ['captcha', 'two-factor code', ['security']],
  ['incognito mode', 'vpn', ['privacy']],
  ['vpn', 'ad blocker', ['privacy']],
  ['data breach', 'account hack', ['security']],
  ['privacy settings', 'location settings', ['privacy']],
  ['public wi-fi', 'mobile hotspot', ['connectivity']],
  ['backup', 'cloud sync', ['storage']],
  ['cloud storage', 'hard drive', ['storage']],
  ['airdrop', 'bluetooth', ['sharing']],
  ['spam folder', 'trash folder', ['email']],
  ['unsubscribe', 'report spam', ['email']],

  // Connected gadgets
  ['wireless earbuds', 'over-ear headphones', ['gadgets']],
  ['apple watch', 'fitbit', ['gadgets']],
  ['kindle', 'ipad', ['gadgets']],
  ['chromebook', 'ipad', ['gadgets']],
  ['smartphone', 'smartwatch', ['gadgets']],
  ['mechanical keyboard', 'gaming mouse', ['gadgets']],
  ['webcam', 'phone camera', ['gadgets']],
  ['microphone', 'webcam', ['gadgets']],
  ['phone tripod', 'selfie stick', ['gadgets']],
  ['portable charger', 'wall charger', ['gadgets']],
  ['usb-c cable', 'lightning cable', ['gadgets']],
  ['smart speaker', 'smart display', ['smart-home']],
  ['smart bulb', 'smart plug', ['smart-home']],
  ['robot vacuum', 'cordless vacuum', ['smart-home']],
  ['airtag', 'tile', ['gadgets']],
  ['vr headset', 'ar glasses', ['gadgets']],
  ['e-reader', 'tablet', ['gadgets']],
  ['wi-fi router', 'mobile hotspot', ['connectivity']],
  ['laptop charger', 'phone charger', ['gadgets']],
  ['webcam', 'security camera', ['gadgets']],

  // Streaming and listening
  ['netflix', 'hulu', ['streaming']],
  ['netflix', 'disney+', ['streaming']],
  ['max', 'prime video', ['streaming']],
  ['youtube', 'netflix', ['streaming']],
  ['spotify', 'pandora', ['music']],
  ['playlist', 'radio station', ['music']],
  ['podcast', 'audiobook', ['audio']],
  ['podcast', 'radio', ['audio']],
  ['livestream', 'podcast', ['media']],
  ['streamer', 'podcaster', ['creators']],
  ['episode', 'clip', ['streaming']],
  ['binge release', 'weekly release', ['streaming']],
  ['skip intro', 'autoplay', ['streaming']],
  ['spoiler warning', 'content warning', ['streaming']],
  ['critic review', 'user review', ['reviews']],
  ['like count', 'view count', ['metrics']],
  ['followers', 'listeners', ['audience']],
  ['recommended feed', 'chronological feed', ['feeds']],
  ['for you page', 'explore page', ['feeds']],
  ['trending page', 'homepage', ['discovery']],
] as const satisfies readonly PairSeed[]

export const internet: WordPack = {
  id: 'internet',
  name: 'Early 30s Internet',
  description: 'Platforms, memes, and online-brain vocab for people who grew up posting.',
  builtIn: true,
  pairs: buildPairs('internet', seeds, [], 250),
}
