import type { WordPack } from '../types'
import { buildPairs, type PairGroup, type PairSeed } from './build'

/**
 * Early 30s Internet: platforms, online culture, and terminally-online vocab.
 */
const seeds = [
  ["instagram", "tiktok", ["apps"]],
  ["group chat", "discord server", ["messaging"]],
  ["podcast", "youtube channel", ["media"]],
  ["doomscrolling", "binge-watching", ["habits"]],
  ["meme", "reaction gif", ["content"]],
  ["notion", "google docs", ["tools"]],
  ["venmo", "zelle", ["payments"]],
  ["spotify wrapped", "letterboxd", ["recaps"]],
  ["reply guy", "lurker", ["personas"]],
  ["unsubscribe", "unfollow", ["actions"]],
  ["group facetime", "zoom call", ["video"]],
  ["screenshot", "screen recording", ["actions"]],
  ["twitch stream", "instagram live", ["streaming"]],
  ["airpods", "apple watch", ["gadgets"]],
  ["subreddit", "facebook group", ["communities"]],
  ["finsta", "burner account", ["accounts"]],
  ["read receipt", "typing bubble", ["texting"]],
  ["wordle", "connections", ["games"]],
  ["algorithm", "for you page", ["feeds"]],
  ["ring light", "green screen", ["setup"]],
  ["stan account", "fan cam", ["fandom"]],
  ["group order", "splitwise", ["logistics"]],
  ["linkedin", "twitter", ["platforms"]],
  ["incognito tab", "private window", ["browsing"]],
  ["roomba", "smart speaker", ["smart-home"]],
  ["unread emails", "browser tabs", ["clutter"]],
  ["ratio", "dunk", ["discourse"]],
  ["cottagecore", "dark academia", ["aesthetics"]],
  ["thirst trap", "humblebrag", ["posting"]],
  ["twitch chat", "live comments", ["chat"]],
  ["crypto bro", "gym bro", ["personas"]],
  ["stitch", "duet", ["tiktok"]],
  ["close friends story", "group dm", ["sharing"]],
  ["password manager", "two-factor", ["security"]],
  ["ghosting", "left on read", ["dating"]],
  ["main character", "npc", ["slang"]],
  ["clickbait", "rage bait", ["content"]],
  ["group playlist", "shared album", ["collab"]],
  ["digital detox", "screen time limit", ["wellness"]],
  ["quote tweet", "repost", ["sharing"]],
] as const satisfies readonly PairSeed[]

const groups = [
  {
    tag: "apps",
    terms: [
    "instagram",
    "tiktok",
    "youtube",
    "twitch",
    "discord",
    "reddit",
    "twitter",
    "threads",
    "bluesky",
    "mastodon",
    "facebook",
    "linkedin",
    "snapchat",
    "be real",
    "pinterest",
    "tumblr",
    "letterboxd",
    "goodreads",
    "spotify",
    "apple music",
    "soundcloud",
    "substack",
    ],
  },
  {
    tag: "messaging",
    terms: [
    "group chat",
    "group dm",
    "discord server",
    "slack channel",
    "whatsapp chat",
    "signal thread",
    "telegram channel",
    "facetime call",
    "zoom call",
    "google meet",
    "voice memo",
    "typing bubble",
    "read receipt",
    "message reaction",
    "thread reply",
    "pinned message",
    "muted chat",
    "archived chat",
    "close friends story",
    "broadcast channel",
    "event invite",
    "shared note",
    ],
  },
  {
    tag: "content",
    terms: [
    "meme",
    "reaction gif",
    "screenshot",
    "screen recording",
    "story post",
    "carousel post",
    "short-form video",
    "livestream",
    "podcast clip",
    "video essay",
    "newsletter",
    "blog post",
    "thread",
    "quote tweet",
    "subtweet",
    "repost",
    "duet",
    "stitch",
    "green screen video",
    "fan edit",
    "explainer",
    "hot take",
    ],
  },
  {
    tag: "discourse",
    terms: [
    "ratio",
    "dunk",
    "pile-on",
    "main character moment",
    "parasocial",
    "discourse cycle",
    "cancelled",
    "soft launch",
    "hard launch",
    "vaguepost",
    "humblebrag",
    "thirst trap",
    "rage bait",
    "clickbait",
    "engagement bait",
    "clout chasing",
    "reply guy",
    "lurker",
    "stan account",
    "burner account",
    "alt account",
    "verified badge",
    ],
  },
  {
    tag: "habits",
    terms: [
    "doomscrolling",
    "hate-watching",
    "binge-watching",
    "tab hoarding",
    "inbox zero",
    "notification badge",
    "screen time limit",
    "digital detox",
    "airplane mode",
    "do not disturb",
    "focus mode",
    "sleep mode",
    "calendar block",
    "link dump",
    "save for later",
    "watch later",
    "read later",
    "unsubscribe spree",
    "unfollow spree",
    "muted keywords",
    "private browsing",
    "password reset",
    ],
  },
  {
    tag: "tools",
    terms: [
    "google docs",
    "notion",
    "figma",
    "canva",
    "miro",
    "trello",
    "asana",
    "linear",
    "jira",
    "slack",
    "discord",
    "zoom",
    "loom",
    "dropbox",
    "google drive",
    "airtable",
    "sheets",
    "calendar",
    "gmail",
    "superhuman",
    "chatgpt",
    "claude",
    ],
  },
  {
    tag: "games",
    terms: [
    "wordle",
    "connections",
    "mini crossword",
    "spelling bee",
    "sudoku",
    "geoguessr",
    "among us",
    "fall guys",
    "minecraft",
    "fortnite",
    "valorant",
    "league of legends",
    "animal crossing",
    "stardew valley",
    "zelda",
    "pokemon go",
    "mario kart",
    "jackbox",
    "gacha game",
    "idle game",
    "speedrun",
    "walkthrough",
    ],
  },
  {
    tag: "shopping",
    terms: [
    "amazon cart",
    "target pickup",
    "instacart",
    "doordash",
    "ubereats",
    "postmates",
    "etsy shop",
    "facebook marketplace",
    "craigslist listing",
    "depop",
    "poshmark",
    "stockx",
    "shopify store",
    "promo code",
    "cashback portal",
    "buy now pay later",
    "wish list",
    "subscribe and save",
    "same-day delivery",
    "porch package",
    "return label",
    "tracking number",
    ],
  },
  {
    tag: "identity",
    terms: [
    "profile picture",
    "bio link",
    "handle",
    "display name",
    "username",
    "avatar",
    "header image",
    "pinned post",
    "highlight reel",
    "close friends list",
    "blocked account",
    "mutuals",
    "followers",
    "following count",
    "verified check",
    "creator account",
    "business account",
    "private account",
    "public account",
    "burner email",
    "password manager",
    "two-factor code",
    ],
  },
  {
    tag: "aesthetics",
    terms: [
    "cottagecore",
    "dark academia",
    "clean girl",
    "coastal grandmother",
    "gorpcore",
    "normcore",
    "barbiecore",
    "quiet luxury",
    "mob wife",
    "indie sleaze",
    "y2k",
    "frutiger aero",
    "vaporwave",
    "lo-fi beats",
    "study with me",
    "morning routine",
    "night routine",
    "desk setup",
    "room tour",
    "shelfie",
    "fit check",
    "get ready with me",
    ],
  },
  {
    tag: "money",
    terms: [
    "venmo",
    "zelle",
    "cash app",
    "paypal",
    "splitwise",
    "group order",
    "shared tab",
    "tip screen",
    "service fee",
    "delivery fee",
    "subscription trial",
    "freemium plan",
    "paywall",
    "patreon",
    "kickstarter",
    "gofundme",
    "crypto wallet",
    "stock app",
    "robinhood",
    "coinbase",
    "autopay",
    "late fee",
    ],
  },
  {
    tag: "gadgets",
    terms: [
    "airpods",
    "noise-canceling headphones",
    "apple watch",
    "fitbit",
    "kindle",
    "ipad",
    "mechanical keyboard",
    "standing desk",
    "ring light",
    "webcam",
    "microphone",
    "phone tripod",
    "portable charger",
    "usb-c cable",
    "dongle",
    "smart speaker",
    "smart bulb",
    "robot vacuum",
    "airtag",
    "tile tracker",
    "e-reader",
    "vr headset",
    ],
  },
] as const satisfies readonly PairGroup[]

export const internet: WordPack = {
  id: "internet",
  name: "Early 30s Internet",
  description: "Platforms, memes, and online-brain vocab for people who grew up posting.",
  builtIn: true,
  pairs: buildPairs("internet", seeds, groups, 250),
}
