import type { WordPack } from '../types'
import { buildPairs, type PairSeed } from './build'

/**
 * Early 30s Internet: platforms, online culture, and familiar digital life.
 *
 * Keep these pairs explicit: broad generated groups made neighboring terms look
 * related without guaranteeing that they produced a fair Woody round.
 */
const seeds = [
  // Platforms and services
  ['instagram', 'tiktok', ['platforms']],
  ['instagram', 'snapchat', ['platforms']],
  ['tiktok', 'youtube shorts', ['platforms']],
  ['youtube', 'twitch', ['platforms']],
  ['reddit', 'discord', ['communities']],
  ['reddit', 'facebook group', ['communities']],
  ['twitter', 'threads', ['platforms']],
  ['twitter', 'facebook', ['platforms']],
  ['facebook', 'instagram', ['platforms']],
  ['linkedin', 'twitter', ['platforms']],
  ['pinterest', 'tumblr', ['platforms']],
  ['imdb', 'goodreads', ['platforms']],
  ['spotify', 'apple music', ['music']],
  ['soundcloud', 'spotify', ['music']],
  ['blog', 'podcast', ['publishing']],
  ['whatsapp', 'facebook messenger', ['messaging']],
  ['imessage', 'whatsapp', ['messaging']],
  ['instagram live', 'tiktok live', ['video']],
  ['venmo', 'zelle', ['payments']],
  ['cash app', 'paypal', ['payments']],

  // Messaging
  ['group chat', 'direct message', ['messaging']],
  ['text message', 'voice memo', ['messaging']],
  ['voice call', 'video call', ['messaging']],
  ['facetime', 'zoom', ['video']],
  ['voicemail', 'text message', ['messaging']],
  ['reaction', 'sticker', ['messaging']],
  ['mute', 'snooze', ['messaging']],
  ['archive', 'delete', ['messaging']],
  ['pin', 'bookmark', ['actions']],
  ['reply', 'forward', ['messaging']],
  ['hashtag', 'mention', ['social']],
  ['dm', 'comment', ['social']],
  ['group text', 'email chain', ['messaging']],
  ['friends', 'strangers', ['audience']],
  ['online', 'offline', ['status']],
  ['sent', 'received', ['messaging']],
  ['notification', 'reminder', ['alerts']],
  ['ringtone', 'vibration', ['alerts']],
  ['phone call', 'text message', ['alerts']],
  ['autocorrect', 'spellcheck', ['messaging']],

  // Posts and media formats
  ['meme', 'reaction gif', ['content']],
  ['screenshot', 'screen recording', ['content']],
  ['photo album', 'slideshow', ['content']],
  ['story', 'post', ['content']],
  ['instagram reel', 'tiktok video', ['video']],
  ['livestream', 'video call', ['video']],
  ['podcast', 'video essay', ['media']],
  ['newsletter', 'blog', ['publishing']],
  ['vlog', 'podcast', ['media']],
  ['tutorial', 'demo', ['content']],
  ['review', 'ranking', ['content']],
  ['unboxing', 'tutorial', ['content']],
  ['reaction video', 'review video', ['video']],
  ['video essay', 'documentary', ['content']],
  ['trailer', 'sneak peek', ['video']],
  ['thumbnail', 'profile picture', ['content']],
  ['caption', 'comment', ['posting']],
  ['thread', 'blog post', ['publishing']],
  ['share', 'copy link', ['sharing']],
  ['lip-sync video', 'dance video', ['tiktok']],
  ['poll', 'quiz', ['interactive']],
  ['q&a', 'interview', ['interactive']],
  ['playlist', 'album', ['music']],
  ['ebook', 'audiobook', ['media']],
  ['gif', 'sticker', ['content']],

  // Common online actions
  ['like', 'bookmark', ['actions']],
  ['send', 'repost', ['actions']],
  ['follow', 'subscribe', ['actions']],
  ['unfollow', 'unsubscribe', ['actions']],
  ['block', 'report', ['safety']],
  ['scroll', 'swipe', ['actions']],
  ['tap', 'click', ['actions']],
  ['upload', 'download', ['actions']],
  ['stream', 'download', ['media']],
  ['log in', 'log out', ['accounts']],
  ['log out', 'delete account', ['accounts']],
  ['search', 'browse', ['actions']],
  ['bookmark', 'download', ['actions']],
  ['copy', 'paste', ['actions']],
  ['crop', 'filter', ['editing']],
  ['zoom in', 'full screen', ['viewing']],
  ['draft', 'post', ['posting']],
  ['publish', 'schedule', ['posting']],
  ['comment', 'review', ['social']],
  ['skip', 'shuffle', ['music']],

  // Social identity and discourse
  ['sponsored post', 'banner ad', ['social']],
  ['clickbait', 'fake news', ['content']],
  ['selfie', 'vacation photo', ['posting']],
  ['joke', 'rant', ['posting']],
  ['single', 'taken', ['posting']],
  ['viewer', 'creator', ['personas']],
  ['troll', 'spammer', ['personas']],
  ['influencer', 'streamer', ['creators']],
  ['follower', 'subscriber', ['audience']],
  ['friend', 'follower', ['audience']],
  ['online friend', 'real-life friend', ['audience']],
  ['verified account', 'fan account', ['accounts']],
  ['fake profile', 'anonymous profile', ['accounts']],
  ['bot', 'spammer', ['accounts']],
  ['public post', 'private message', ['accounts']],
  ['bio', 'status message', ['identity']],
  ['username', 'profile picture', ['identity']],
  ['selfie', 'group photo', ['identity']],
  ['hashtag', 'keyword', ['discovery']],
  ['forum', 'chat room', ['communities']],

  // Browsing habits and settings
  ['scrolling', 'binge-watching', ['habits']],
  ['reading', 'posting', ['habits']],
  ['tab', 'window', ['clutter']],
  ['battery life', 'storage space', ['metrics']],
  ['silent', 'vibrate', ['settings']],
  ['alarm', 'timer', ['settings']],
  ['brightness', 'volume', ['settings']],
  ['website', 'app', ['privacy']],
  ['playlist', 'watchlist', ['saving']],
  ['autoplay', 'shuffle', ['media']],
  ['notification', 'pop-up', ['alerts']],
  ['scrolling', 'searching', ['feeds']],
  ['ad', 'pop-up', ['browsing']],
  ['password', 'pin', ['security']],
  ['link', 'button', ['browsing']],
  ['history', 'bookmarks', ['privacy']],
  ['tabs', 'bookmarks', ['browsing']],
  ['wi-fi', 'cell signal', ['connectivity']],
  ['battery icon', 'signal icon', ['settings']],
  ['grocery delivery', 'restaurant delivery', ['habits']],

  // Familiar digital tools
  ['google docs', 'google sheets', ['tools']],
  ['canva', 'photoshop', ['tools']],
  ['zoom', 'microsoft teams', ['tools']],
  ['slack', 'discord', ['tools']],
  ['dropbox', 'icloud', ['storage']],
  ['icloud', 'google drive', ['storage']],
  ['spreadsheet', 'presentation', ['tools']],
  ['gmail', 'yahoo mail', ['email']],
  ['chatgpt', 'gemini', ['ai']],
  ['siri', 'alexa', ['assistants']],
  ['google maps', 'waze', ['navigation']],
  ['chrome', 'safari', ['browsers']],
  ['firefox', 'chrome', ['browsers']],
  ['google search', 'bing', ['search']],
  ['grammar checker', 'spellchecker', ['writing']],
  ['password manager', 'antivirus', ['security']],
  ['calendar', 'reminders', ['tools']],
  ['notes', 'checklist', ['tools']],
  ['qr code', 'barcode', ['codes']],
  ['link', 'attachment', ['sharing']],

  // Online and mobile games
  ['wordle', 'crossword', ['games']],
  ['wordle', 'sudoku', ['games']],
  ['crossword', 'sudoku', ['games']],
  ['hangman', 'wordle', ['games']],
  ['among us', 'clue', ['games']],
  ['minecraft', 'fortnite', ['games']],
  ['fortnite', 'call of duty', ['games']],
  ['call of duty', 'grand theft auto', ['games']],
  ['tetris', 'solitaire', ['games']],
  ['farmville', 'animal crossing', ['games']],
  ['zelda', 'pokemon', ['games']],
  ['pokemon go', 'candy crush', ['games']],
  ['mario kart', 'smash bros.', ['games']],
  ['mario party', 'among us', ['games']],
  ['candy crush', 'angry birds', ['games']],
  ['roblox', 'minecraft', ['games']],
  ['the sims', 'animal crossing', ['games']],
  ['chess', 'solitaire', ['games']],
  ['trivia', 'crossword', ['games']],
  ['mobile game', 'console game', ['games']],
  ['cheat code', 'game guide', ['gaming']],
  ['jigsaw puzzle', 'trivia quiz', ['gaming']],
  ['team game', 'solo game', ['gaming']],
  ['voice chat', 'text chat', ['gaming']],
  ['lag', 'glitch', ['gaming']],

  // Shopping and money
  ['amazon', 'target', ['shopping']],
  ['etsy', 'ebay', ['shopping']],
  ['craigslist', 'facebook marketplace', ['shopping']],
  ['ebay', 'facebook marketplace', ['shopping']],
  ['doordash', 'uber eats', ['delivery']],
  ['instacart', 'doordash', ['delivery']],
  ['promo code', 'gift card', ['shopping']],
  ['shopping cart', 'wish list', ['shopping']],
  ['delivery app', 'rideshare app', ['apps']],
  ['same-day delivery', 'standard shipping', ['shipping']],
  ['tracking number', 'order number', ['shipping']],
  ['return', 'exchange', ['shopping']],
  ['free trial', 'free sample', ['subscriptions']],
  ['subscription', 'one-time purchase', ['payments']],
  ['patreon', 'kickstarter', ['funding']],
  ['gofundme', 'kickstarter', ['funding']],
  ['robinhood', 'coinbase', ['finance']],
  ['credit card', 'debit card', ['payments']],
  ['apple pay', 'google pay', ['payments']],
  ['credit card', 'bank transfer', ['payments']],

  // Privacy and security
  ['password', 'fingerprint', ['security']],
  ['passcode', 'face id', ['security']],
  ['face id', 'fingerprint', ['security']],
  ['password', 'security question', ['security']],
  ['spam', 'phishing', ['security']],
  ['scammer', 'catfish', ['security']],
  ['hacker', 'scammer', ['security']],
  ['computer virus', 'ransomware', ['security']],
  ['scam call', 'phishing email', ['security']],
  ['captcha', 'security question', ['security']],
  ['vpn', 'antivirus', ['privacy']],
  ['ad blocker', 'antivirus', ['privacy']],
  ['data breach', 'account hack', ['security']],
  ['camera', 'microphone', ['privacy']],
  ['public wi-fi', 'mobile hotspot', ['connectivity']],
  ['backup', 'restore', ['storage']],
  ['cloud storage', 'hard drive', ['storage']],
  ['airdrop', 'text message', ['sharing']],
  ['spam folder', 'trash folder', ['email']],
  ['unsubscribe', 'report spam', ['email']],

  // Connected gadgets
  ['wireless earbuds', 'over-ear headphones', ['gadgets']],
  ['apple watch', 'fitbit', ['gadgets']],
  ['kindle', 'ipad', ['gadgets']],
  ['chromebook', 'ipad', ['gadgets']],
  ['smartphone', 'smartwatch', ['gadgets']],
  ['mechanical keyboard', 'gaming mouse', ['gadgets']],
  ['webcam', 'phone camera', ['gadgets']],
  ['microphone', 'webcam', ['gadgets']],
  ['phone tripod', 'selfie stick', ['gadgets']],
  ['portable charger', 'wall charger', ['gadgets']],
  ['usb-c cable', 'lightning cable', ['gadgets']],
  ['smart speaker', 'bluetooth speaker', ['smart-home']],
  ['smart bulb', 'smart plug', ['smart-home']],
  ['robot vacuum', 'cordless vacuum', ['smart-home']],
  ['airtag', 'key finder', ['gadgets']],
  ['vr headset', 'game console', ['gadgets']],
  ['e-reader', 'tablet', ['gadgets']],
  ['router', 'modem', ['connectivity']],
  ['laptop charger', 'phone charger', ['gadgets']],
  ['webcam', 'security camera', ['gadgets']],

  // Streaming and listening
  ['netflix', 'hulu', ['streaming']],
  ['netflix', 'disney+', ['streaming']],
  ['max', 'prime video', ['streaming']],
  ['youtube', 'netflix', ['streaming']],
  ['spotify', 'pandora', ['music']],
  ['playlist', 'radio station', ['music']],
  ['podcast', 'audiobook', ['audio']],
  ['podcast', 'radio', ['audio']],
  ['livestream', 'podcast', ['media']],
  ['streamer', 'podcaster', ['creators']],
  ['episode', 'clip', ['streaming']],
  ['episode', 'movie', ['streaming']],
  ['skip', 'rewind', ['streaming']],
  ['spoiler warning', 'content warning', ['streaming']],
  ['critic review', 'user review', ['reviews']],
  ['likes', 'views', ['metrics']],
  ['followers', 'listeners', ['audience']],
  ['funny video', 'news video', ['feeds']],
  ['photos', 'videos', ['feeds']],
  ['trending topic', 'breaking news', ['discovery']],
] as const satisfies readonly PairSeed[]

export const internet: WordPack = {
  id: 'internet',
  name: 'Early 30s Internet',
  description: 'Platforms, memes, and online-brain vocab for people who grew up posting.',
  builtIn: true,
  pairs: buildPairs('internet', seeds, [], 250),
}
