import type { WordPack } from '../types'

/**
 * Pop Culture: shows, movies, music, and celebrity-adjacent picks.
 */
export const popCulture: WordPack = {
  id: 'pop-culture',
  name: 'Pop Culture',
  description: 'Shows, movies, and music the group actually argues about.',
  builtIn: true,
  pairs: [
    { id: 'pop-culture-001', a: 'the office', b: 'parks and recreation', tags: ['tv'] },
    { id: 'pop-culture-002', a: 'marvel', b: 'dc', tags: ['movies'] },
    { id: 'pop-culture-003', a: 'taylor swift', b: 'beyonce', tags: ['music'] },
    { id: 'pop-culture-004', a: 'netflix', b: 'hulu', tags: ['streaming'] },
    { id: 'pop-culture-005', a: 'reality tv', b: 'true crime', tags: ['genres'] },
    { id: 'pop-culture-006', a: 'oscars', b: 'grammys', tags: ['awards'] },
    { id: 'pop-culture-007', a: 'boy band', b: 'girl group', tags: ['music'] },
    { id: 'pop-culture-008', a: 'rom com', b: 'sitcom', tags: ['genres'] },
    { id: 'pop-culture-009', a: 'sequel', b: 'reboot', tags: ['movies'] },
    { id: 'pop-culture-010', a: 'movie theater', b: 'drive-in', tags: ['venues'] },
    { id: 'pop-culture-011', a: 'concert', b: 'music festival', tags: ['live'] },
    { id: 'pop-culture-012', a: 'the bachelor', b: 'love island', tags: ['reality'] },
    { id: 'pop-culture-013', a: 'harry potter', b: 'lord of the rings', tags: ['franchises'] },
    { id: 'pop-culture-014', a: 'stand-up special', b: 'sketch show', tags: ['comedy'] },
    { id: 'pop-culture-015', a: 'anime', b: 'cartoon', tags: ['animation'] },
    { id: 'pop-culture-016', a: 'vinyl record', b: 'cassette tape', tags: ['formats'] },
    { id: 'pop-culture-017', a: 'red carpet', b: 'press junket', tags: ['events'] },
    { id: 'pop-culture-018', a: 'season finale', b: 'series premiere', tags: ['tv'] },
    { id: 'pop-culture-019', a: 'blockbuster', b: 'indie film', tags: ['movies'] },
    { id: 'pop-culture-020', a: 'jump scare', b: 'plot twist', tags: ['tropes'] },
    { id: 'pop-culture-021', a: 'k-pop', b: 'hip hop', tags: ['genres'] },
    { id: 'pop-culture-022', a: 'super bowl halftime', b: 'coachella set', tags: ['performances'] },
    { id: 'pop-culture-023', a: 'game show', b: 'talk show', tags: ['tv'] },
    { id: 'pop-culture-024', a: 'spoiler', b: 'trailer', tags: ['media'] },
    { id: 'pop-culture-025', a: 'broadway', b: 'west end', tags: ['theater'] },
    { id: 'pop-culture-026', a: 'nintendo', b: 'playstation', tags: ['gaming'] },
    { id: 'pop-culture-027', a: 'documentary', b: 'biopic', tags: ['genres'] },
    { id: 'pop-culture-028', a: 'comic book', b: 'graphic novel', tags: ['print'] },
    { id: 'pop-culture-029', a: 'boy meets world', b: 'friends', tags: ['sitcoms'] },
    { id: 'pop-culture-030', a: 'stranger things', b: 'squid game', tags: ['hits'] },
    { id: 'pop-culture-031', a: 'pixar', b: 'studio ghibli', tags: ['animation'] },
    { id: 'pop-culture-032', a: 'dj set', b: 'live band', tags: ['music'] },
    { id: 'pop-culture-033', a: 'meme stock', b: 'viral dance', tags: ['viral'] },
    { id: 'pop-culture-034', a: 'karaoke', b: 'open mic', tags: ['performance'] },
    { id: 'pop-culture-035', a: 'movie snack', b: 'concession stand', tags: ['cinema'] },
    { id: 'pop-culture-036', a: 'fan theory', b: 'easter egg', tags: ['fandom'] },
    { id: 'pop-culture-037', a: 'reunion special', b: 'spin-off', tags: ['tv'] },
    { id: 'pop-culture-038', a: 'award speech', b: 'walk-up song', tags: ['moments'] },
  ],
}
