import type { WordPack } from '../types'
import { buildPairs, type PairSeed } from './build'

/**
 * Pop Culture: broad American entertainment and nostalgia references.
 */
const seeds = [
  // Franchises, characters, and fictional worlds
  ["marvel", "dc", ["comics"]],
  ["star wars", "star trek", ["sci-fi"]],
  ["harry potter", "lord of the rings", ["fantasy"]],
  ["pokemon", "digimon", ["nostalgia"]],
  ["mario", "sonic", ["games"]],
  ["pixar", "dreamworks", ["animation"]],
  ["disney channel", "nickelodeon", ["nostalgia"]],
  ["batman", "spider-man", ["superheroes"]],
  ["superman", "captain america", ["superheroes"]],
  ["wonder woman", "captain marvel", ["superheroes"]],
  ["joker", "green goblin", ["villains"]],
  ["avengers", "justice league", ["superheroes"]],
  ["x-men", "fantastic four", ["superheroes"]],
  ["guardians of the galaxy", "suicide squad", ["superheroes"]],
  ["hunger games", "divergent", ["young-adult"]],
  ["twilight", "vampire diaries", ["fantasy"]],
  ["jaws", "alien", ["movies"]],
  ["james bond", "mission impossible", ["action"]],
  ["fast and furious", "transformers", ["action"]],
  ["toy story", "shrek", ["animation"]],
  ["frozen", "moana", ["animation"]],
  ["finding nemo", "little mermaid", ["animation"]],
  ["lion king", "jungle book", ["animation"]],
  ["aladdin", "mulan", ["animation"]],
  ["cinderella", "sleeping beauty", ["animation"]],
  ["mickey mouse", "bugs bunny", ["animation"]],
  ["scooby-doo", "tom and jerry", ["animation"]],
  ["power rangers", "teenage mutant ninja turtles", ["nostalgia"]],
  ["game of thrones", "the witcher", ["fantasy"]],
  ["walking dead", "the last of us", ["apocalypse"]],
  ["avatar", "dune", ["sci-fi"]],
  ["the matrix", "inception", ["sci-fi"]],
  ["ghostbusters", "men in black", ["comedy"]],
  ["rocky", "karate kid", ["sports"]],
  ["cobra kai", "ted lasso", ["nostalgia"]],
  ["mean girls", "clueless", ["comedy"]],
  ["legally blonde", "the devil wears prada", ["comedy"]],
  ["princess diaries", "miss congeniality", ["comedy"]],
  ["high school musical", "camp rock", ["nostalgia"]],
  ["freaky friday", "parent trap", ["comedy"]],
  ["home alone", "elf", ["holiday"]],
  ["nightmare before christmas", "corpse bride", ["animation"]],
  ["indiana jones", "pirates of the caribbean", ["adventure"]],
  ["terminator", "robocop", ["sci-fi"]],
  ["alien", "predator", ["sci-fi"]],
  ["godzilla", "king kong", ["monsters"]],
  ["kill bill", "john wick", ["action"]],
  ["ocean's eleven", "the italian job", ["heist"]],
  ["national treasure", "the da vinci code", ["adventure"]],
  ["top gun", "pearl harbor", ["action"]],

  // Television
  ["the office", "parks and rec", ["tv"]],
  ["friends", "seinfeld", ["tv"]],
  ["new girl", "how i met your mother", ["tv"]],
  ["brooklyn nine-nine", "community", ["tv"]],
  ["abbott elementary", "modern family", ["tv"]],
  ["30 rock", "veep", ["tv"]],
  ["succession", "white lotus", ["tv"]],
  ["kitchen nightmares", "bar rescue", ["tv"]],
  ["grey's anatomy", "er", ["tv"]],
  ["law and order", "csi", ["tv"]],
  ["the bachelor", "love is blind", ["reality-tv"]],
  ["survivor", "amazing race", ["reality-tv"]],
  ["american idol", "the voice", ["reality-tv"]],
  ["rupaul's drag race", "project runway", ["reality-tv"]],
  ["top chef", "great british bake off", ["reality-tv"]],
  ["jeopardy", "wheel of fortune", ["game-shows"]],
  ["snl", "key and peele", ["comedy"]],
  ["the daily show", "last week tonight", ["comedy"]],
  ["gossip girl", "pretty little liars", ["teen-tv"]],
  ["gilmore girls", "dawson's creek", ["teen-tv"]],
  ["the oc", "one tree hill", ["teen-tv"]],
  ["euphoria", "skins", ["teen-tv"]],
  ["bridgerton", "downton abbey", ["period-tv"]],
  ["the crown", "bridgerton", ["period-drama"]],
  ["black mirror", "twilight zone", ["sci-fi"]],
  ["ted lasso", "friday night lights", ["sports-tv"]],
  ["sex and the city", "insecure", ["tv"]],
  ["broad city", "girls", ["tv"]],
  ["breaking bad", "ozark", ["crime-tv"]],
  ["the sopranos", "the wire", ["crime-tv"]],
  ["lost", "yellowjackets", ["mystery-tv"]],
  ["buffy", "charmed", ["fantasy-tv"]],
  ["smallville", "arrow", ["superhero-tv"]],
  ["dexter", "you", ["thriller-tv"]],
  ["true detective", "mindhunter", ["crime-tv"]],
  ["orange is the new black", "glow", ["tv"]],
  ["schitt's creek", "ted lasso", ["comedy"]],
  ["this is us", "parenthood", ["family-tv"]],
  ["handmaid's tale", "black mirror", ["dystopia"]],
  ["stranger things", "the x-files", ["sci-fi"]],

  // Movies
  ["titanic", "the notebook", ["romance"]],
  ["bridesmaids", "the hangover", ["comedy"]],
  ["superbad", "booksmart", ["comedy"]],
  ["get out", "us", ["horror"]],
  ["scream", "i know what you did last summer", ["horror"]],
  ["halloween", "friday the 13th", ["horror"]],
  ["the conjuring", "insidious", ["horror"]],
  ["a quiet place", "bird box", ["horror"]],
  ["knives out", "clue", ["mystery"]],
  ["la la land", "the greatest showman", ["musicals"]],
  ["mamma mia", "pitch perfect", ["musicals"]],
  ["bohemian rhapsody", "rocketman", ["music-movies"]],
  ["the social network", "steve jobs", ["biopics"]],
  ["wolf of wall street", "the big short", ["finance-movies"]],
  ["goodfellas", "the godfather", ["crime"]],
  ["pulp fiction", "reservoir dogs", ["crime"]],
  ["13 going on 30", "27 dresses", ["romance"]],
  ["how to lose a guy in 10 days", "10 things i hate about you", ["romance"]],
  ["love actually", "the holiday", ["romance"]],
  ["when harry met sally", "you've got mail", ["romance"]],
  ["crazy rich asians", "my big fat greek wedding", ["romance"]],
  ["wedding crashers", "bridesmaids", ["comedy"]],
  ["napoleon dynamite", "juno", ["indie-movies"]],
  ["little miss sunshine", "the royal tenenbaums", ["indie-movies"]],
  ["school of rock", "sister act", ["music-movies"]],
  ["mrs. doubtfire", "tootsie", ["comedy"]],
  ["cast away", "the martian", ["survival"]],
  ["armageddon", "deep impact", ["disaster"]],
  ["independence day", "war of the worlds", ["aliens"]],
  ["e.t.", "close encounters", ["aliens"]],
  ["oppenheimer", "the imitation game", ["biopics"]],
  ["barbie", "legally blonde", ["comedy"]],
  ["parasite", "saltburn", ["thriller"]],
  ["everything everywhere all at once", "inception", ["multiverse"]],
  ["die hard", "speed", ["action"]],
  ["taken", "bourne identity", ["action"]],
  ["clueless", "10 things i hate about you", ["teen-movies"]],
  ["mean girls", "easy a", ["teen-movies"]],
  ["black swan", "whiplash", ["drama"]],
  ["bring it on", "step up", ["competition"]],

  // Music artists
  ["beyonce", "rihanna", ["music"]],
  ["taylor swift", "olivia rodrigo", ["music"]],
  ["britney spears", "christina aguilera", ["music"]],
  ["backstreet boys", "nsync", ["music"]],
  ["spice girls", "destiny's child", ["music"]],
  ["lady gaga", "madonna", ["music"]],
  ["katy perry", "lady gaga", ["music"]],
  ["ariana grande", "selena gomez", ["music"]],
  ["miley cyrus", "demi lovato", ["music"]],
  ["justin bieber", "shawn mendes", ["music"]],
  ["drake", "kendrick lamar", ["music"]],
  ["jay-z", "kanye west", ["music"]],
  ["nicki minaj", "cardi b", ["music"]],
  ["eminem", "50 cent", ["music"]],
  ["snoop dogg", "dr. dre", ["music"]],
  ["tupac", "biggie", ["music"]],
  ["lil wayne", "drake", ["music"]],
  ["missy elliott", "lauryn hill", ["music"]],
  ["usher", "justin timberlake", ["music"]],
  ["bruno mars", "the weeknd", ["music"]],
  ["bad bunny", "j balvin", ["music"]],
  ["shakira", "jennifer lopez", ["music"]],
  ["sza", "frank ocean", ["music"]],
  ["lizzo", "doja cat", ["music"]],
  ["billie eilish", "lorde", ["music"]],
  ["olivia rodrigo", "sabrina carpenter", ["music"]],
  ["dua lipa", "charli xcx", ["music"]],
  ["chappell roan", "sabrina carpenter", ["music"]],
  ["alicia keys", "john legend", ["music"]],
  ["adele", "kelly clarkson", ["music"]],
  ["ed sheeran", "john mayer", ["music"]],
  ["maroon 5", "onerepublic", ["music"]],
  ["coldplay", "imagine dragons", ["music"]],
  ["fall out boy", "panic at the disco", ["music"]],
  ["paramore", "evanescence", ["music"]],
  ["green day", "blink-182", ["music"]],
  ["linkin park", "limp bizkit", ["music"]],
  ["foo fighters", "nirvana", ["music"]],
  ["red hot chili peppers", "green day", ["music"]],
  ["radiohead", "coldplay", ["music"]],
  ["the beatles", "the rolling stones", ["music"]],
  ["queen", "elton john", ["music"]],
  ["fleetwood mac", "abba", ["music"]],
  ["metallica", "guns n' roses", ["music"]],
  ["u2", "bruce springsteen", ["music"]],
  ["garth brooks", "shania twain", ["music"]],
  ["carrie underwood", "kelly clarkson", ["music"]],
  ["daft punk", "calvin harris", ["music"]],
  ["bts", "one direction", ["music"]],
  ["one direction", "jonas brothers", ["music"]],

  // Millennial nostalgia and games
  ["cartoon network", "nickelodeon", ["nostalgia"]],
  ["mtv", "vh1", ["nostalgia"]],
  ["blockbuster", "redbox", ["nostalgia"]],
  ["aim", "msn messenger", ["nostalgia"]],
  ["myspace", "facebook", ["nostalgia"]],
  ["ipod", "walkman", ["nostalgia"]],
  ["game boy", "nintendo ds", ["games"]],
  ["wii sports", "mario kart", ["games"]],
  ["guitar hero", "rock band", ["games"]],
  ["neopets", "webkinz", ["nostalgia"]],
  ["club penguin", "neopets", ["nostalgia"]],
  ["tamagotchi", "furby", ["nostalgia"]],
  ["beanie babies", "pokemon cards", ["nostalgia"]],
  ["razr", "sidekick", ["nostalgia"]],
  ["blackberry", "sidekick", ["nostalgia"]],
  ["burned cd", "ipod playlist", ["nostalgia"]],
  ["limewire", "napster", ["nostalgia"]],
  ["dvd", "vhs", ["nostalgia"]],
  ["lizzie mcguire", "that's so raven", ["nostalgia"]],
  ["boy meets world", "saved by the bell", ["nostalgia"]],
  ["rugrats", "hey arnold", ["nostalgia"]],
  ["spongebob", "fairly oddparents", ["nostalgia"]],
  ["dexter's laboratory", "powerpuff girls", ["nostalgia"]],
  ["arthur", "magic school bus", ["nostalgia"]],
  ["sesame street", "barney", ["nostalgia"]],
  ["blue's clues", "dora the explorer", ["nostalgia"]],
  ["pokemon cards", "yu-gi-oh cards", ["games"]],
  ["xbox", "playstation", ["games"]],
  ["nintendo", "sega", ["games"]],
  ["halo", "call of duty", ["games"]],

  // Formats, fandom, awards, and live entertainment
  ["oscars", "grammys", ["awards"]],
  ["emmys", "golden globes", ["awards"]],
  ["tonys", "oscars", ["awards"]],
  ["cannes", "sundance", ["film-festivals"]],
  ["met gala", "fashion week", ["celebrity"]],
  ["super bowl halftime", "grammys performance", ["live-events"]],
  ["leading role", "supporting role", ["acting"]],
  ["reboot", "remake", ["media"]],
  ["prequel", "sequel", ["media"]],
  ["spin-off", "reboot", ["media"]],
  ["cameo", "guest star", ["acting"]],
  ["trailer", "commercial", ["media"]],
  ["soundtrack", "score", ["movies"]],
  ["opening credits", "closing credits", ["tv"]],
  ["plot twist", "cliffhanger", ["story"]],
  ["flashback", "time jump", ["story"]],
  ["alternate timeline", "time loop", ["story"]],
  ["hero", "antihero", ["characters"]],
  ["villain", "antihero", ["characters"]],
  ["meet cute", "love triangle", ["romance"]],
  ["canon", "headcanon", ["fandom"]],
  ["easter egg", "cameo", ["fandom"]],
  ["spoiler alert", "content warning", ["media"]],
  ["sitcom", "sketch comedy", ["genres"]],
  ["slasher", "monster movie", ["genres"]],
  ["psychological thriller", "murder mystery", ["genres"]],
  ["sci-fi", "fantasy", ["genres"]],
  ["documentary", "biopic", ["genres"]],
  ["legal drama", "medical drama", ["genres"]],
  ["dating show", "game show", ["genres"]],
  ["talk show", "podcast", ["media"]],
  ["stand-up special", "concert film", ["live-entertainment"]],
  ["broadway", "west end", ["theater"]],
  ["play", "musical", ["theater"]],
  ["matinee", "evening show", ["theater"]],
  ["opening night", "closing night", ["theater"]],
  ["curtain call", "encore", ["live-entertainment"]],
  ["arena tour", "stadium tour", ["live-events"]],
  ["coachella", "lollapalooza", ["live-events"]],
  ["season premiere", "season finale", ["tv"]],
] as const satisfies readonly PairSeed[]

export const popCulture: WordPack = {
  id: "pop-culture",
  name: "Pop Culture",
  description: "Movies, music, TV, celebrity, and nostalgia without needing deep fandom knowledge.",
  builtIn: true,
  pairs: buildPairs("pop-culture", seeds, [], 250),
}
