import type { WordPack } from '../types'
import { buildPairs, type PairGroup, type PairSeed } from './build'

/**
 * Pop Culture: broad American entertainment and nostalgia references.
 */
const seeds = [
  ["marvel", "dc", ["comics"]],
  ["star wars", "star trek", ["sci-fi"]],
  ["beyonce", "rihanna", ["music"]],
  ["taylor swift", "olivia rodrigo", ["music"]],
  ["barbie", "oppenheimer", ["movies"]],
  ["the office", "parks and rec", ["tv"]],
  ["pokemon", "digimon", ["nostalgia"]],
  ["harry potter", "lord of the rings", ["fantasy"]],
  ["pixar", "dreamworks", ["animation"]],
  ["netflix", "hbo max", ["streaming"]],
  ["disney channel", "nickelodeon", ["nostalgia"]],
  ["grammys", "oscars", ["awards"]],
  ["red carpet", "press tour", ["celebrity"]],
  ["super bowl halftime", "coachella", ["events"]],
  ["rom-com", "action movie", ["genres"]],
  ["sitcom", "drama", ["tv"]],
  ["theme song", "soundtrack", ["music"]],
  ["boy band", "girl group", ["music"]],
  ["reality tv", "game show", ["tv"]],
  ["celebrity couple", "nepo baby", ["celebrity"]],
  ["booktok", "movie trailer", ["media"]],
  ["spoiler", "plot twist", ["story"]],
  ["villain", "antihero", ["characters"]],
  ["cameo", "post-credit scene", ["movies"]],
  ["album drop", "single drop", ["music"]],
  ["fan theory", "easter egg", ["fandom"]],
  ["reboot", "remake", ["media"]],
  ["season finale", "series finale", ["tv"]],
  ["cold open", "monologue", ["tv"]],
  ["stand-up special", "comedy tour", ["comedy"]],
  ["broadway", "west end", ["theater"]],
  ["anime", "manga", ["media"]],
  ["oscars speech", "acceptance speech", ["awards"]],
  ["press junket", "podcast interview", ["media"]],
  ["viral dance", "challenge video", ["internet"]],
  ["soundtrack", "score", ["movies"]],
  ["leading role", "supporting role", ["acting"]],
  ["box office", "streaming numbers", ["business"]],
] as const satisfies readonly PairSeed[]

const groups = [
  {
    tag: "franchises",
    terms: [
    "marvel",
    "dc",
    "star wars",
    "star trek",
    "jurassic park",
    "fast and furious",
    "mission impossible",
    "james bond",
    "harry potter",
    "lord of the rings",
    "hunger games",
    "twilight",
    "avatar",
    "transformers",
    "toy story",
    "shrek",
    "frozen",
    "despicable me",
    "minions",
    "pokemon",
    "mario",
    "sonic",
    ],
  },
  {
    tag: "music",
    terms: [
    "beyonce",
    "rihanna",
    "taylor swift",
    "olivia rodrigo",
    "billie eilish",
    "dua lipa",
    "sabrina carpenter",
    "ariana grande",
    "lady gaga",
    "madonna",
    "britney spears",
    "janet jackson",
    "bruno mars",
    "the weeknd",
    "drake",
    "kendrick lamar",
    "bad bunny",
    "sza",
    "doja cat",
    "usher",
    "justin timberlake",
    "miley cyrus",
    ],
  },
  {
    tag: "tv",
    terms: [
    "the office",
    "parks and rec",
    "friends",
    "seinfeld",
    "abbott elementary",
    "new girl",
    "community",
    "brooklyn nine-nine",
    "succession",
    "white lotus",
    "the bear",
    "euphoria",
    "stranger things",
    "game of thrones",
    "house of the dragon",
    "the last of us",
    "the crown",
    "bridgerton",
    "grey anatomy",
    "law and order",
    "survivor",
    "the bachelor",
    ],
  },
  {
    tag: "movies",
    terms: [
    "barbie",
    "oppenheimer",
    "everything everywhere all at once",
    "parasite",
    "get out",
    "knives out",
    "la la land",
    "black panther",
    "crazy rich asians",
    "top gun maverick",
    "mean girls",
    "clueless",
    "legally blonde",
    "the devil wears prada",
    "the social network",
    "the matrix",
    "inception",
    "interstellar",
    "titanic",
    "the notebook",
    "bridesmaids",
    "superbad",
    ],
  },
  {
    tag: "awards",
    terms: [
    "oscars",
    "grammys",
    "emmys",
    "tonys",
    "golden globes",
    "sag awards",
    "mtv awards",
    "vmas",
    "billboard awards",
    "cannes",
    "sundance",
    "tribeca",
    "red carpet",
    "acceptance speech",
    "in memoriam",
    "best picture",
    "album of the year",
    "song of the year",
    "best new artist",
    "lead actor",
    "supporting actor",
    "lifetime achievement",
    ],
  },
  {
    tag: "fandom",
    terms: [
    "fan theory",
    "easter egg",
    "spoiler",
    "plot twist",
    "ship",
    "canon",
    "headcanon",
    "retcon",
    "reboot",
    "remake",
    "spin-off",
    "prequel",
    "sequel",
    "crossover",
    "cameo",
    "post-credit scene",
    "trailer drop",
    "teaser",
    "leak",
    "press tour",
    "panel",
    "comic-con",
    ],
  },
  {
    tag: "nostalgia",
    terms: [
    "disney channel",
    "nickelodeon",
    "cartoon network",
    "pbs kids",
    "mtv",
    "vh1",
    "trl",
    "american idol",
    "guitar hero",
    "rock band",
    "nintendo ds",
    "game boy advance",
    "wii sports",
    "neopets",
    "club penguin",
    "webkinz",
    "aim away message",
    "myspace profile",
    "burned cd",
    "ipod nano",
    "blockbuster",
    "netflix dvd",
    ],
  },
  {
    tag: "genres",
    terms: [
    "rom-com",
    "teen comedy",
    "coming-of-age",
    "action movie",
    "heist movie",
    "spy thriller",
    "superhero movie",
    "horror movie",
    "slasher",
    "psychological thriller",
    "sci-fi",
    "fantasy",
    "musical",
    "documentary",
    "biopic",
    "sports movie",
    "legal drama",
    "medical drama",
    "prestige drama",
    "sitcom",
    "reality tv",
    "game show",
    ],
  },
  {
    tag: "celebrity",
    terms: [
    "celebrity couple",
    "breakup rumor",
    "nepo baby",
    "publicist",
    "paparazzi",
    "tabloid headline",
    "cover story",
    "profile piece",
    "podcast interview",
    "late-night interview",
    "press junket",
    "brand deal",
    "fashion campaign",
    "red carpet look",
    "met gala look",
    "tour outfit",
    "hair transformation",
    "apology video",
    "notes app apology",
    "relationship reveal",
    "hard launch",
    "engagement ring",
    ],
  },
  {
    tag: "events",
    terms: [
    "super bowl halftime",
    "coachella",
    "lollapalooza",
    "governors ball",
    "sxsw",
    "comic-con",
    "album release party",
    "movie premiere",
    "season premiere",
    "season finale",
    "series finale",
    "live reunion",
    "aftershow",
    "watch party",
    "midnight screening",
    "listening party",
    "stadium tour",
    "arena tour",
    "festival set",
    "encore",
    "standing ovation",
    "meet and greet",
    ],
  },
  {
    tag: "story",
    terms: [
    "hero",
    "villain",
    "antihero",
    "sidekick",
    "mentor",
    "love interest",
    "comic relief",
    "final girl",
    "chosen one",
    "underdog",
    "rival",
    "betrayal",
    "redemption arc",
    "origin story",
    "training montage",
    "meet cute",
    "third-act breakup",
    "cliffhanger",
    "flashback",
    "time jump",
    "alternate timeline",
    "multiverse",
    ],
  },
  {
    tag: "theater",
    terms: [
    "broadway",
    "west end",
    "touring production",
    "off-broadway",
    "playbill",
    "cast album",
    "opening night",
    "closing night",
    "understudy",
    "swing",
    "ensemble",
    "matinee",
    "standing ovation",
    "curtain call",
    "stage door",
    "orchestra seats",
    "balcony seats",
    "tony nomination",
    "revival",
    "jukebox musical",
    "original musical",
    "straight play",
    ],
  },
] as const satisfies readonly PairGroup[]

export const popCulture: WordPack = {
  id: "pop-culture",
  name: "Pop Culture",
  description: "Movies, music, TV, celebrity, and nostalgia without needing deep fandom knowledge.",
  builtIn: true,
  pairs: buildPairs("pop-culture", seeds, groups, 250),
}
