import type { WordPack } from '../types'
import { buildPairs, type PairGroup, type PairSeed } from './build'

/**
 * Work and School: office, campus, grad-school, and productivity vocabulary.
 */
const seeds = [
  // Supplies
  ['pencil', 'pen', ['supplies']],
  ['marker', 'highlighter', ['supplies']],
  ['crayon', 'colored pencil', ['supplies']],
  ['notebook', 'binder', ['supplies']],
  ['folder', 'envelope', ['supplies']],
  ['paper', 'notecard', ['supplies']],
  ['clipboard', 'notepad', ['supplies']],
  ['stapler', 'hole punch', ['supplies']],
  ['paper clip', 'binder clip', ['supplies']],
  ['scissors', 'paper cutter', ['supplies']],
  ['ruler', 'yardstick', ['supplies']],
  ['compass', 'protractor', ['supplies']],
  ['calculator', 'abacus', ['supplies']],
  ['chalk', 'marker', ['supplies']],
  ['chalkboard', 'whiteboard', ['supplies']],
  ['eraser', 'correction tape', ['supplies']],
  ['glue', 'tape', ['supplies']],
  ['index card', 'flashcard', ['supplies']],
  ['textbook', 'workbook', ['supplies']],
  ['dictionary', 'thesaurus', ['reference']],
  ['planner', 'calendar', ['planning']],
  ['backpack', 'briefcase', ['bags']],
  ['lunchbox', 'tote bag', ['bags']],
  ['name tag', 'id badge', ['identification']],
  ['pushpin', 'magnet', ['supplies']],

  // Desks and equipment
  ['desk', 'table', ['furniture']],
  ['chair', 'stool', ['furniture']],
  ['bookshelf', 'filing cabinet', ['storage']],
  ['desk lamp', 'floor lamp', ['lighting']],
  ['keyboard', 'touchscreen', ['equipment']],
  ['mouse', 'trackpad', ['equipment']],
  ['monitor', 'projector', ['equipment']],
  ['webcam', 'camera', ['equipment']],
  ['microphone', 'voice recorder', ['equipment']],
  ['headphones', 'headset', ['equipment']],
  ['printer', 'copier', ['equipment']],
  ['scanner', 'copier', ['equipment']],
  ['shredder', 'paper cutter', ['equipment']],
  ['desk phone', 'cell phone', ['equipment']],
  ['charger', 'power bank', ['equipment']],
  ['flash drive', 'hard drive', ['storage']],
  ['tablet', 'chromebook', ['computers']],
  ['desktop', 'laptop', ['computers']],
  ['water bottle', 'coffee mug', ['desk']],
  ['pen cup', 'pencil case', ['desk']],
  ['sticky note', 'notecard', ['supplies']],
  ['bulletin board', 'whiteboard', ['displays']],
  ['cubicle', 'private office', ['workplaces']],
  ['standing desk', 'treadmill desk', ['furniture']],
  ['filing cabinet', 'locker', ['storage']],

  // School and workplace spaces
  ['classroom', 'lecture hall', ['school-places']],
  ['laboratory', 'workshop', ['workspaces']],
  ['cafeteria', 'dining hall', ['school-places']],
  ['gymnasium', 'athletic field', ['school-places']],
  ['dormitory', 'apartment', ['housing']],
  ['campus', 'office park', ['places']],
  ['quad', 'courtyard', ['places']],
  ['hallway', 'stairwell', ['places']],
  ['computer lab', 'science lab', ['school-places']],
  ['art room', 'music room', ['school-places']],
  ['study room', 'conference room', ['rooms']],
  ['faculty lounge', 'break room', ['rooms']],
  ['bookstore', 'stationery store', ['campus']],
  ['playground', 'athletic field', ['school-places']],
  ['campus shuttle', 'school bus', ['transportation']],
  ['lecture hall', 'auditorium', ['school-places']],
  ['seminar room', 'classroom', ['school-places']],
  ['library', 'computer lab', ['study-places']],
  ['dormitory', 'fraternity house', ['housing']],
  ['student center', 'recreation center', ['campus']],
  ['mailroom', 'copy room', ['workplaces']],
  ['reception desk', 'security desk', ['workplaces']],
  ['corner office', 'home office', ['workplaces']],
  ['warehouse', 'factory', ['workplaces']],
  ['art studio', 'science lab', ['workspaces']],

  // People and roles
  ['teacher', 'professor', ['educators']],
  ['tutor', 'coach', ['guides']],
  ['principal', 'dean', ['school-leaders']],
  ['student', 'trainee', ['learners']],
  ['classmate', 'coworker', ['peers']],
  ['lab partner', 'study partner', ['peers']],
  ['professor', 'lecturer', ['educators']],
  ['substitute teacher', 'student teacher', ['educators']],
  ['principal', 'superintendent', ['school-leaders']],
  ['manager', 'supervisor', ['work-leaders']],
  ['director', 'executive', ['work-leaders']],
  ['founder', 'owner', ['business-roles']],
  ['employee', 'contractor', ['workers']],
  ['intern', 'apprentice', ['learners']],
  ['mentor', 'advisor', ['guides']],
  ['recruiter', 'career counselor', ['career-roles']],
  ['librarian', 'archivist', ['information-roles']],
  ['receptionist', 'office assistant', ['office-roles']],
  ['custodian', 'groundskeeper', ['support-roles']],
  ['accountant', 'bookkeeper', ['finance-roles']],
  ['engineer', 'architect', ['technical-roles']],
  ['illustrator', 'animator', ['creative-roles']],
  ['writer', 'editor', ['writing-roles']],
  ['researcher', 'analyst', ['research-roles']],
  ['salesperson', 'marketer', ['business-roles']],

  // Courses and subjects
  ['math', 'science', ['subjects']],
  ['algebra', 'geometry', ['math']],
  ['calculus', 'statistics', ['math']],
  ['biology', 'chemistry', ['science']],
  ['physics', 'astronomy', ['science']],
  ['history', 'geography', ['humanities']],
  ['civics', 'economics', ['social-science']],
  ['literature', 'creative writing', ['language-arts']],
  ['grammar', 'spelling', ['language-arts']],
  ['art', 'music', ['arts']],
  ['theater', 'dance', ['performing-arts']],
  ['computer science', 'engineering', ['technical']],
  ['psychology', 'sociology', ['social-science']],
  ['philosophy', 'religion', ['humanities']],
  ['anatomy', 'physiology', ['science']],
  ['geology', 'environmental science', ['science']],
  ['french', 'spanish', ['languages']],
  ['orchestra', 'band', ['music']],
  ['choir', 'orchestra', ['performing-arts']],
  ['debate', 'speech', ['communication']],
  ['gym', 'health', ['school-subjects']],
  ['woodshop', 'metal shop', ['shop-class']],
  ['ceramics', 'painting', ['arts']],
  ['photography', 'film', ['media-arts']],
  ['accounting', 'finance', ['business-subjects']],

  // Assignments and evaluation
  ['quiz', 'test', ['exams']],
  ['midterm', 'final', ['exams']],
  ['essay', 'report', ['assignments']],
  ['thesis', 'dissertation', ['research']],
  ['homework', 'classwork', ['assignments']],
  ['worksheet', 'problem set', ['assignments']],
  ['book report', 'lab report', ['assignments']],
  ['presentation', 'speech', ['assignments']],
  ['group project', 'solo project', ['projects']],
  ['open-book test', 'take-home test', ['exams']],
  ['multiple choice', 'true or false', ['questions']],
  ['oral exam', 'written exam', ['exams']],
  ['outline', 'mind map', ['planning']],
  ['bibliography', 'footnotes', ['citations']],
  ['research paper', 'case study', ['assignments']],
  ['capstone', 'thesis', ['projects']],
  ['internship', 'practicum', ['training']],
  ['lab work', 'fieldwork', ['learning']],
  ['lecture', 'seminar', ['classes']],
  ['tutorial', 'workshop', ['learning']],
  ['office hours', 'review session', ['study']],
  ['study guide', 'flashcards', ['study']],
  ['transcript', 'report card', ['records']],
  ['diploma', 'certificate', ['credentials']],
  ['rubric', 'checklist', ['evaluation']],

  // Learning and work activities
  ['read', 'write', ['activities']],
  ['study', 'practice', ['learning']],
  ['memorize', 'review', ['learning']],
  ['highlight', 'underline', ['reading']],
  ['annotate', 'summarize', ['reading']],
  ['brainstorm', 'outline', ['planning']],
  ['calculate', 'estimate', ['math']],
  ['measure', 'weigh', ['measurement']],
  ['survey', 'experiment', ['investigation']],
  ['observe', 'measure', ['investigation']],
  ['present', 'demonstrate', ['communication']],
  ['discuss', 'debate', ['communication']],
  ['ask', 'answer', ['communication']],
  ['teach', 'coach', ['instruction']],
  ['collaborate', 'compete', ['group-activities']],
  ['type', 'handwrite', ['writing']],
  ['print', 'photocopy', ['documents']],
  ['staple', 'bind', ['documents']],
  ['file', 'archive', ['documents']],
  ['plan', 'improvise', ['planning']],
  ['attend', 'skip', ['attendance']],
  ['enroll', 'audit', ['classes']],
  ['proofread', 'edit', ['writing']],
  ['cite', 'quote', ['writing']],
  ['clock in', 'clock out', ['work-routines']],

  // Communication and software
  ['slack', 'teams', ['software']],
  ['zoom', 'webex', ['software']],
  ['word', 'google docs', ['software']],
  ['spreadsheet', 'database', ['software']],
  ['powerpoint', 'keynote', ['software']],
  ['canvas', 'blackboard', ['software']],
  ['chromebook', 'macbook', ['computers']],
  ['windows', 'macos', ['software']],
  ['jira', 'trello', ['software']],
  ['notion', 'confluence', ['software']],
  ['email', 'text message', ['communication']],
  ['phone interview', 'video interview', ['communication']],
  ['voicemail', 'voice memo', ['communication']],
  ['memo', 'announcement', ['communication']],
  ['newsletter', 'yearbook', ['publications']],
  ['question', 'suggestion', ['feedback']],
  ['survey', 'poll', ['feedback']],
  ['sign-up sheet', 'attendance sheet', ['forms']],
  ['one-on-one', 'group meeting', ['meetings']],
  ['staff meeting', 'class meeting', ['meetings']],
  ['conference', 'convention', ['events']],
  ['interview', 'audition', ['evaluations']],
  ['webinar', 'conference call', ['remote-events']],
  ['career fair', 'college fair', ['events']],
  ['whiteboard', 'flip chart', ['presentation-tools']],

  // Careers and work-school parallels
  ['resume', 'portfolio', ['careers']],
  ['cover letter', 'personal statement', ['applications']],
  ['internship', 'apprenticeship', ['training']],
  ['promotion', 'raise', ['advancement']],
  ['salary', 'hourly wage', ['pay']],
  ['bonus', 'commission', ['pay']],
  ['benefits', 'perks', ['compensation']],
  ['vacation', 'sick leave', ['time-off']],
  ['full-time', 'part-time', ['work-arrangements']],
  ['remote', 'hybrid', ['work-arrangements']],
  ['office', 'home office', ['workplaces']],
  ['commute', 'road trip', ['work-travel']],
  ['id badge', 'keycard', ['access']],
  ['timesheet', 'punch card', ['timekeeping']],
  ['paycheck', 'stipend', ['pay']],
  ['union', 'professional association', ['organizations']],
  ['job offer', 'admission letter', ['acceptance']],
  ['performance review', 'report card', ['evaluation']],
  ['promotion', 'transfer', ['milestones']],
  ['layoff', 'expulsion', ['dismissal']],
  ['onboarding', 'orientation', ['introductions']],
  ['office party', 'school dance', ['social-events']],
  ['business trip', 'field trip', ['travel']],
  ['break room', 'student lounge', ['shared-spaces']],
  ['company picnic', 'office party', ['social-events']],

  // School life
  ['semester', 'quarter', ['school-calendar']],
  ['freshman', 'sophomore', ['year-levels']],
  ['junior', 'senior', ['year-levels']],
  ['undergraduate', 'graduate student', ['students']],
  ['major', 'minor', ['degree-programs']],
  ['elective', 'required course', ['courses']],
  ['public school', 'private school', ['schools']],
  ['community college', 'university', ['schools']],
  ['day school', 'boarding school', ['schools']],
  ['preschool', 'kindergarten', ['schools']],
  ['recess', 'lunch break', ['breaks']],
  ['spring break', 'summer break', ['school-calendar']],
  ['scholarship', 'grant', ['financial-aid']],
  ['tuition', 'school fees', ['school-costs']],
  ['grade', 'score', ['evaluation']],
  ['pass-fail', 'letter grade', ['grading-systems']],
  ['attendance', 'participation', ['coursework']],
  ['absence', 'tardiness', ['attendance']],
  ['valedictorian', 'salutatorian', ['students']],
  ['school club', 'sports team', ['student-groups']],
  ['fraternity', 'sorority', ['student-groups']],
  ['homeroom', 'study hall', ['class-periods']],
  ['detention', 'suspension', ['discipline']],
  ['school newspaper', 'yearbook', ['publications']],
  ['master\'s degree', 'doctoral degree', ['degrees']],
] as const satisfies readonly PairSeed[]

const groups = [] as const satisfies readonly PairGroup[]

export const workSchool: WordPack = {
  id: 'work-school',
  name: 'Work & School',
  description: 'Office, campus, and professional-life pairs for educated friend groups.',
  builtIn: true,
  pairs: buildPairs('work-school', seeds, groups, 250),
}
