import type { WordPack } from '../types'
import { buildPairs, type PairGroup, type PairSeed } from './build'

/**
 * Work and School: office, campus, grad-school, and productivity vocabulary.
 */
const seeds = [
  ["google calendar", "outlook calendar", ["tools"]],
  ["standup", "status meeting", ["meetings"]],
  ["slack", "teams", ["tools"]],
  ["spreadsheet", "weekly report", ["documents"]],
  ["office hours", "study group", ["school"]],
  ["midterm", "final", ["school"]],
  ["resume", "cover letter", ["careers"]],
  ["mentor", "manager", ["people"]],
  ["intern", "new grad", ["careers"]],
  ["whiteboard", "sticky notes", ["planning"]],
  ["deadline", "milestone", ["planning"]],
  ["rubric", "syllabus", ["school"]],
  ["thesis", "capstone", ["school"]],
  ["laptop stand", "monitor arm", ["desk"]],
  ["coffee badge", "lunch badge", ["office"]],
  ["commute", "hybrid day", ["work"]],
  ["expense report", "receipt", ["finance"]],
  ["performance review", "promotion packet", ["career"]],
  ["networking event", "career fair", ["career"]],
  ["research paper", "case study", ["school"]],
  ["office kitchen", "break room", ["places"]],
  ["printer jam", "wifi outage", ["annoyances"]],
  ["tuition", "student loans", ["finance"]],
  ["group project", "solo assignment", ["school"]],
  ["brainstorm", "workshop", ["meetings"]],
  ["notebook", "planner", ["supplies"]],
  ["campus tour", "orientation", ["school"]],
  ["lecture hall", "seminar room", ["places"]],
  ["lab partner", "project partner", ["people"]],
  ["email thread", "calendar invite", ["communication"]],
  ["raise hand", "ask in chat", ["meetings"]],
  ["desk chair", "standing desk", ["desk"]],
  ["promotion", "lateral move", ["career"]],
  ["reference letter", "recommendation letter", ["career"]],
  ["office party", "team lunch", ["social"]],
  ["sabbatical", "pto", ["time-off"]],
  ["reading list", "watch list", ["study"]],
  ["department chair", "dean", ["school"]],
] as const satisfies readonly PairSeed[]

const groups = [
  {
    tag: "meetings",
    terms: [
    "standup",
    "sync",
    "check-in",
    "one-on-one",
    "manager sync",
    "all-hands",
    "town hall",
    "retrospective",
    "planning meeting",
    "kickoff",
    "readout",
    "debrief",
    "working session",
    "brainstorm",
    "workshop",
    "office hours",
    "seminar",
    "lecture",
    "lab meeting",
    "study group",
    "review session",
    "defense",
    "conference talk",
    ],
  },
  {
    tag: "documents",
    terms: [
    "agenda",
    "notes doc",
    "meeting minutes",
    "status update",
    "project brief",
    "product spec",
    "design doc",
    "research memo",
    "case study",
    "slide deck",
    "appendix deck",
    "spreadsheet",
    "dashboard",
    "roadmap",
    "tracker",
    "rubric",
    "syllabus",
    "worksheet",
    "problem set",
    "lab report",
    "research paper",
    "thesis",
    "appendix",
    ],
  },
  {
    tag: "roles",
    terms: [
    "intern",
    "new grad",
    "associate",
    "senior analyst",
    "manager",
    "director",
    "vp",
    "founder",
    "advisor",
    "mentor",
    "sponsor",
    "professor",
    "lecturer",
    "teaching assistant",
    "research assistant",
    "lab partner",
    "project partner",
    "classmate",
    "alumni",
    "recruiter",
    "hiring manager",
    "reference",
    ],
  },
  {
    tag: "career",
    terms: [
    "resume",
    "cover letter",
    "portfolio",
    "linkedin profile",
    "referral",
    "phone screen",
    "technical interview",
    "case interview",
    "take-home assignment",
    "onsite interview",
    "offer letter",
    "negotiation",
    "background check",
    "start date",
    "onboarding",
    "probation period",
    "performance review",
    "promotion packet",
    "raise conversation",
    "lateral move",
    "exit interview",
    "alumni network",
    ],
  },
  {
    tag: "planning",
    terms: [
    "deadline",
    "milestone",
    "deliverable",
    "dependency",
    "blocker",
    "scope",
    "priority",
    "backlog",
    "sprint",
    "quarterly goal",
    "okr",
    "roadmap",
    "timeline",
    "launch date",
    "review cycle",
    "approval chain",
    "stakeholder",
    "owner",
    "handoff",
    "follow-up",
    "action item",
    "next step",
    ],
  },
  {
    tag: "tools",
    terms: [
    "slack",
    "teams",
    "google meet",
    "zoom",
    "notion",
    "confluence",
    "jira board",
    "linear issue",
    "asana task",
    "trello card",
    "github",
    "figma",
    "miro",
    "google docs",
    "google sheets",
    "excel",
    "powerpoint",
    "keynote",
    "canvas",
    "blackboard",
    "gradescope",
    "overleaf",
    ],
  },
  {
    tag: "campus",
    terms: [
    "lecture hall",
    "seminar room",
    "library stacks",
    "study room",
    "dorm lounge",
    "dining hall",
    "quad",
    "student center",
    "registrar",
    "financial aid office",
    "career center",
    "campus bookstore",
    "lab building",
    "rec center",
    "parking permit office",
    "bike rack",
    "campus shuttle",
    "fraternity row",
    "club fair",
    "graduation stage",
    "alumni center",
    "campus coffee shop",
    ],
  },
  {
    tag: "desk",
    terms: [
    "laptop",
    "external monitor",
    "monitor arm",
    "laptop stand",
    "keyboard",
    "mouse",
    "trackpad",
    "desk mat",
    "notebook",
    "planner",
    "sticky notes",
    "index cards",
    "sticky flags",
    "highlighter",
    "whiteboard marker",
    "water bottle",
    "coffee mug",
    "desk lamp",
    "webcam",
    "microphone",
    "noise-canceling headphones",
    "desk chair",
    "standing desk",
    ],
  },
  {
    tag: "communication",
    terms: [
    "email thread",
    "reply all",
    "forwarded invite",
    "calendar hold",
    "calendar invite",
    "reschedule note",
    "out-of-office reply",
    "status ping",
    "slack dm",
    "channel mention",
    "thread reply",
    "emoji reaction",
    "doc comment",
    "suggesting mode",
    "version history",
    "tracked changes",
    "presentation notes",
    "voice memo",
    "announcement post",
    "office hours signup",
    "anonymous feedback",
    "course evaluation",
    ],
  },
  {
    tag: "finance",
    terms: [
    "tuition",
    "student loans",
    "stipend",
    "grant",
    "scholarship",
    "fellowship",
    "research funding",
    "expense report",
    "receipt",
    "reimbursement",
    "per diem",
    "corporate card",
    "invoice",
    "purchase order",
    "budget request",
    "headcount plan",
    "salary band",
    "equity grant",
    "bonus target",
    "401k match",
    "open enrollment",
    "commuter benefit",
    ],
  },
  {
    tag: "culture",
    terms: [
    "team lunch",
    "mentor coffee",
    "happy hour",
    "onsite week",
    "onsite week",
    "hybrid day",
    "remote day",
    "casual friday",
    "hackathon",
    "demo day",
    "poster session",
    "career fair",
    "networking event",
    "guest lecture",
    "club meeting",
    "student org",
    "department mixer",
    "holiday party",
    "office potluck",
    "graduation party",
    "alumni dinner",
    "thank-you note",
    ],
  },
  {
    tag: "friction",
    terms: [
    "printer jam",
    "wifi outage",
    "vpn issue",
    "password reset",
    "calendar conflict",
    "double booking",
    "meeting overrun",
    "missing attachment",
    "broken link",
    "version conflict",
    "merge conflict",
    "file permission",
    "access request",
    "late submission",
    "extension request",
    "waitlist",
    "prerequisite hold",
    "room change",
    "syllabus update",
    "grade dispute",
    "missed deadline",
    "scope creep",
    ],
  },
] as const satisfies readonly PairGroup[]

export const workSchool: WordPack = {
  id: "work-school",
  name: "Work & School",
  description: "Office, campus, and professional-life pairs for educated friend groups.",
  builtIn: true,
  pairs: buildPairs("work-school", seeds, groups, 250),
}
