import type { WordPack } from '../types'

/**
 * Work & School: office life, adulting logistics, and campus memories.
 */
export const workSchool: WordPack = {
  id: 'work-school',
  name: 'Work & School',
  description: 'Office life, adulting money stuff, and campus memories.',
  builtIn: true,
  pairs: [
    { id: 'work-school-001', a: '401k', b: 'roth ira', tags: ['money'] },
    { id: 'work-school-002', a: 'standup meeting', b: 'one on one', tags: ['meetings'] },
    { id: 'work-school-003', a: 'slack', b: 'email', tags: ['comms'] },
    { id: 'work-school-004', a: 'group project', b: 'lab partner', tags: ['school'] },
    { id: 'work-school-005', a: 'internship', b: 'apprenticeship', tags: ['early-career'] },
    { id: 'work-school-006', a: 'promotion', b: 'raise', tags: ['career'] },
    { id: 'work-school-007', a: 'commute', b: 'work from home', tags: ['work-life'] },
    { id: 'work-school-008', a: 'resume', b: 'cover letter', tags: ['job-hunt'] },
    { id: 'work-school-009', a: 'pop quiz', b: 'final exam', tags: ['school'] },
    { id: 'work-school-010', a: 'office party', b: 'happy hour', tags: ['work-social'] },
    { id: 'work-school-011', a: 'spreadsheet', b: 'slide deck', tags: ['deliverables'] },
    { id: 'work-school-012', a: 'lecture hall', b: 'conference room', tags: ['rooms'] },
    { id: 'work-school-013', a: 'student loan', b: 'mortgage', tags: ['debt'] },
    { id: 'work-school-014', a: 'performance review', b: 'report card', tags: ['evaluation'] },
    { id: 'work-school-015', a: 'coffee badging', b: 'quiet quitting', tags: ['office-trends'] },
    { id: 'work-school-016', a: 'syllabus', b: 'job description', tags: ['documents'] },
    { id: 'work-school-017', a: 'office kitchen', b: 'break room', tags: ['spaces'] },
    { id: 'work-school-018', a: 'sick day', b: 'mental health day', tags: ['time-off'] },
    { id: 'work-school-019', a: 'group study', b: 'office hours', tags: ['school'] },
    { id: 'work-school-020', a: 'onboarding', b: 'orientation', tags: ['starting'] },
    { id: 'work-school-021', a: 'deadline', b: 'due date', tags: ['time'] },
    { id: 'work-school-022', a: 'networking event', b: 'career fair', tags: ['career'] },
    { id: 'work-school-023', a: 'whiteboard', b: 'chalkboard', tags: ['classroom'] },
    { id: 'work-school-024', a: 'pto request', b: 'hall pass', tags: ['permission'] },
    { id: 'work-school-025', a: 'coworker', b: 'classmate', tags: ['people'] },
    { id: 'work-school-026', a: 'lunch break', b: 'recess', tags: ['breaks'] },
    { id: 'work-school-027', a: 'expense report', b: 'tax return', tags: ['paperwork'] },
    { id: 'work-school-028', a: 'group chat mute', b: 'do not disturb', tags: ['focus'] },
    { id: 'work-school-029', a: 'dorm room', b: 'studio apartment', tags: ['living'] },
    { id: 'work-school-030', a: 'gpa', b: 'credit score', tags: ['numbers'] },
    { id: 'work-school-031', a: 'thesis', b: 'capstone', tags: ['projects'] },
    { id: 'work-school-032', a: 'badge', b: 'lanyard', tags: ['id'] },
    { id: 'work-school-033', a: 'gap year', b: 'sabbatical', tags: ['breaks'] },
    { id: 'work-school-034', a: 'ergonomic chair', b: 'standing desk', tags: ['setup'] },
    { id: 'work-school-035', a: 'group email', b: 'reply all', tags: ['email'] },
    { id: 'work-school-036', a: 'tenure', b: 'seniority', tags: ['status'] },
    { id: 'work-school-037', a: 'water cooler', b: 'vending machine', tags: ['office'] },
    { id: 'work-school-038', a: 'overtime', b: 'extra credit', tags: ['extra-effort'] },
  ],
}
